# <center>Title Topic Modeling</center>
---

In [1]:
import pandas as pd
import nltk
import os
import sys
from nltk.corpus import stopwords
nltk.download('stopwords')

project_root_path = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root_path not in sys.path:
    sys.path.append(project_root_path)
from PreProcessing.pre_processing import PreProcessing
import numpy as np
import spacy as sp

[nltk_data] Downloading package stopwords to /home/ester/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
df = pd.read_csv("../data/english_youtube_titles.csv")

In [3]:
def remove_repetion_caracteres(string, max_repetition=2):
    if not string:
        return string
    
    result = string[0]
    count = 1
    
    for i in range(1, len(string)):
        if string[i] == string[i-1]:
            count += 1
            if count <= max_repetition:
                result += string[i]
        else:
            count = 1
            result += string[i]
    
    return result

def preprocess_text_pipeline(#input_csv_path='./data/dataFrame.csv', 
                              #output_csv_path='./data/dataFrame.csv',
                              df,
                              stopwords_file='stopwords.txt',
                              text_column="comments"):
   
    stem = sp.load("en_core_web_sm")
    pp = PreProcessing(language="en")
    
    custom_stopwords = [line.strip() for line in open(stopwords_file, 'r', encoding='utf-8')]
    english_stopwords = set(stopwords.words('english'))
    
    # Adiciona stopwords à lista da classe PreProcessing
    pp.append_stopwords_list(list(english_stopwords - set(pp.stopwords)) + custom_stopwords)

    def preprocessing(text):
        if pd.isna(text):
            return np.nan

        tokens = stem(text.lower()) # Processo de lematização da biblioteca spaCy - retorna a lista dos tokens do texto
        text = ' '.join([text for token in tokens for text in token.lemma_.strip().split()]) # Junta estes tokens na ordem do texto bruto
        text = pp.remove_stopwords(text) # Remove stopwords presentes
        text = pp.lowercase_unidecode(text) # Coloca tudo em lowercase e remove acento
        text = pp.remove_stopwords(text) # Remove stopwords presentes 
        text = pp.remove_tweet_marking(text) # Remove @ ou # seguido de 1 ou mais carcteres e n ' ' seguidos
        text = remove_repetion_caracteres(text) # Remove a repetição de caracteres ex: gooool -> gool
        text = pp.remove_urls(text) # Remove http\S+ *, ou seja, qualquer http seguido de 1 ou mais caracteres e os espaços no final
        text = pp.remove_punctuation(text) # Remove os sinais de pontuação e reorganiza os espaços
        text = pp.remove_numbers(text) # Remove os números
        text = pp.remove_n(text, n=3) # Remove palavras de tamanho <= n(n=3)
        
        return text

    df['clean_text'] = df[text_column].apply(preprocessing)
    return df

In [4]:
#df_clean = preprocess_text_pipeline(df=df, text_column='title')
#display(df_clean)

In [5]:
#df_clean.to_csv("../data/preprocessed_english_titles")

In [6]:
df_clean = pd.read_csv("../data/preprocessed_english_titles.csv")
display(df_clean)

,Unnamed: 0,video_id,title,youtube_video_link,clean_text
0,0,BFQ8gqvkjz8,nasthug | Boiler Room Tokyo: Tohji Presents u-ha,https://www.youtube.com/watch?v=BFQ8gqvkjz8,nasthug boiler room tokyo tohji present
1,1,X928ajAsdMM,Puddle Of Mudd - Livin' On Borrowed Time (Offi...,https://www.youtube.com/watch?v=X928ajAsdMM,puddle mudd livin borrow time official audio
2,2,PWbMXDvviTw,The Titans: Rise of the Unstoppable,https://www.youtube.com/watch?v=PWbMXDvviTw,titans rise unstoppable
3,3,o62RwF_s4Jw,'Rabbi' Shmuley: a walking antisemitic stereotype,https://www.youtube.com/watch?v=o62RwF_s4Jw,rabbi shmuley walk antisemitic stereotype
4,4,QJWplEkDyck,What Just Happened On Our Earth!!! September 2...,https://www.youtube.com/watch?v=QJWplEkDyck,happen earth september naturaldisaster
...,...,...,...,...,...
257054,257054,cl1QZWF6e_E,Utter Silence Is Fragile,https://www.youtube.com/watch?v=cl1QZWF6e_E,utter silence fragile
257055,257055,cgKtKsefXyQ,Willy Deville - Just Your Friends,https://www.youtube.com/watch?v=cgKtKsefXyQ,willy deville friend
257056,257056,6qO4TxA7U3c,Putin's Missiles 'Hit' NATO Nation's Train Car...,https://www.youtube.com/watch?v=6qO4TxA7U3c,putin missile nato nation train carry atacms s...
257057,257057,ojLpPQiFguE,"Stop the ""Moonlighting"" Bill. Tharman to Resig...",https://www.youtube.com/watch?v=ojLpPQiFguE,stop moonlighting bill tharman resign online z...
257058,257058,rNBc4XdkfPA,I'm In Public Ma'am!!,https://www.youtube.com/watch?v=rNBc4XdkfPA,public

In [7]:
#df_clean = df_clean.drop(columns=["Unnamed: 0.1", "Unnamed: 0", "lang"])

#f_clean = df_clean[df_clean["title"].notna()]            
#df_clean = df_clean[df_clean["title"].str.strip() != ""]  

display(df_clean)
#df_clean.to_csv("../data/preprocessed_english_titles")

,Unnamed: 0,video_id,title,youtube_video_link,clean_text
0,0,BFQ8gqvkjz8,nasthug | Boiler Room Tokyo: Tohji Presents u-ha,https://www.youtube.com/watch?v=BFQ8gqvkjz8,nasthug boiler room tokyo tohji present
1,1,X928ajAsdMM,Puddle Of Mudd - Livin' On Borrowed Time (Offi...,https://www.youtube.com/watch?v=X928ajAsdMM,puddle mudd livin borrow time official audio
2,2,PWbMXDvviTw,The Titans: Rise of the Unstoppable,https://www.youtube.com/watch?v=PWbMXDvviTw,titans rise unstoppable
3,3,o62RwF_s4Jw,'Rabbi' Shmuley: a walking antisemitic stereotype,https://www.youtube.com/watch?v=o62RwF_s4Jw,rabbi shmuley walk antisemitic stereotype
4,4,QJWplEkDyck,What Just Happened On Our Earth!!! September 2...,https://www.youtube.com/watch?v=QJWplEkDyck,happen earth september naturaldisaster
...,...,...,...,...,...
257054,257054,cl1QZWF6e_E,Utter Silence Is Fragile,https://www.youtube.com/watch?v=cl1QZWF6e_E,utter silence fragile
257055,257055,cgKtKsefXyQ,Willy Deville - Just Your Friends,https://www.youtube.com/watch?v=cgKtKsefXyQ,willy deville friend
257056,257056,6qO4TxA7U3c,Putin's Missiles 'Hit' NATO Nation's Train Car...,https://www.youtube.com/watch?v=6qO4TxA7U3c,putin missile nato nation train carry atacms s...
257057,257057,ojLpPQiFguE,"Stop the ""Moonlighting"" Bill. Tharman to Resig...",https://www.youtube.com/watch?v=ojLpPQiFguE,stop moonlighting bill tharman resign online z...
257058,257058,rNBc4XdkfPA,I'm In Public Ma'am!!,https://www.youtube.com/watch?v=rNBc4XdkfPA,public

In [8]:
df_teste = df_clean.sample(n=150000, random_state=42)
display(df_teste)
df_teste.to_csv("../data/df_teste.csv")

,Unnamed: 0,video_id,title,youtube_video_link,clean_text
212198,212198,s6elID_u28s,Author John Elder Robison Speaks at Clarkson U...,https://www.youtube.com/watch?v=s6elID_u28s,author john elder robison speak clarkson unive...
163787,163787,wL8DVHuWI7Y,"VØJ, Narvent - Memory Reboot (4K Music Video)",https://www.youtube.com/watch?v=wL8DVHuWI7Y,narvent memory reboot music video
36932,36932,1XxeZaEnwZ0,TRUMP CONTRO TUTTI - MAZZUCCO live - Puntata 3...,https://www.youtube.com/watch?v=1XxeZaEnwZ0,trump contro tutti mazzucco live puntata
69401,69401,0vUBHqyJs8o,"Cryptocurrency's Market Correction, and Why Yo...",https://www.youtube.com/watch?v=0vUBHqyJs8o,cryptocurrency market correction worry like
22587,22587,kVaMn_x1wEE,"Frontline Combat Sees Russia Capture Ukraine ""...",https://www.youtube.com/watch?v=kVaMn_x1wEE,frontline combat russia capture ukraine invinc...
...,...,...,...,...,...
41318,41318,d-cuqXnFM_g,This charity is determined to get UK Veterans ...,https://www.youtube.com/watch?v=d-cuqXnFM_g,charity determined veteran street
155192,155192,TcILlS3B61U,Antony C. Sutton - The Capitalist Communist Co...,https://www.youtube.com/watch?v=TcILlS3B61U,antony sutton capitalist communist conspiracy
184195,184195,m55rWL9WA7M,UNBOXING The Feast of Hemlock Vale Campaign! (...,https://www.youtube.com/watch?v=m55rWL9WA7M,unbox feast hemlock vale campaign arkham horror
113558,113558,ZXKK5b-zDB4,Your Secret Invisible Force You Aren't Taking ...,https://www.youtube.com/watch?v=ZXKK5b-zDB4,secret invisible force advantage energy magic ...
6223,6223,giFRe1v0YjQ,Evidence that ties Cheney & MOSSAD to 9/11,https://www.youtube.com/watch?v=giFRe1v0YjQ,evidence cheney mossad

In [ ]:
from topicmodeling import run_topic_modeling

# Executa o BERTopic, definindo os parâmentros e usando o kmeans
#if run_topic_modeling(): print("Modelagem concluída.")
loaded_model, probs, topics = run_topic_modeling()

/home/ester/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

{'nr_topics': 10, 'language': 'english', 'calculate_probabilities': True, 'verbose': False, 'top_n_words': 10, 'umap_model': UMAP(metric='cosine', n_components=5, n_neighbors=10, random_state=42), 'hdbscan_model': HDBSCAN(min_cluster_size=50, min_samples=5, prediction_data=True), 'ctfidf_model': ClassTfidfTransformer(reduce_frequent_words=True)}

In [ ]:
topicos = [t for t in loaded_model.get_topics().keys() if t != -1]
fig = loaded_model.visualize_barchart(topics=topicos, n_words=10)
fig.update_layout(title_text="",  height=110 +60 * len(topicos),
    margin=dict(l=120, r=20, t=30, b=20))
fig.show()

In [ ]:
a = loaded_model.get_topic_info()
a

,Topic,Count,Name,Representation,Representative_Docs
0,-1,41091,-1_trump_live_israel_biden,"[trump, live, israel, biden, video, world, gaz...",[harry miller free speech high court victory a...
1,0,24844,0_official_video_trailer_music,"[official, video, trailer, music, lyric, earth...","[vote official movie trailer, super frequency ..."
2,1,22064,1_ukraine_trump_russia_kamala,"[ukraine, trump, russia, kamala, israel, biden...",[emergency american bomber nuclear alert israe...
3,2,5168,2_taiwan_taiwanplus_news_china,"[taiwan, taiwanplus, news, china, chinese, tai...","[taiwan taiwan news august taiwanplus news, ch..."
4,3,2233,3_crypto_bitcoin_gold_silver,"[crypto, bitcoin, gold, silver, ripple, dinar,...","[bitcoin crypto quick update, bitcoin crypto q..."
5,4,1441,4_food_farmer_coffee_recipe,"[food, farmer, coffee, recipe, markz, chicken,...","[coffee markz, coffee markz, coffee markz]"
6,5,1275,5_covid_vaccine_pandemic_cancer,"[covid, vaccine, pandemic, cancer, health, doc...","[covid vaccine push emergency redact news, doc..."
7,6,1234,6_hurricane_climate_milton_helene,"[hurricane, climate, milton, helene, water, to...",[tropical storm milton form gulf head florida ...
8,7,181,7_crochet_stitch_hand_pattern,"[crochet, stitch, hand, pattern, embroidery, s...",[easy cute amigurumi crochet pattern beginner ...
9,8,119,8_council_school_meeting_homeschool,"[council, school, meeting, homeschool, educati...","[council meeting february, brave girl wake tea..."