### **1. Correlation of sharing with views**
___

In [20]:
file_path = "data/youtube_links.jsonl"

#### **1.1 Sharing count per video**
____

In [2]:
import pandas as pd
import gzip
import json
from tqdm.notebook import tqdm

dados_processados = []

try:
    with open(file_path, "rt", encoding="utf-8") as f:
        for line in tqdm(f, desc="Processando URLs"):
            try:
                data = json.loads(line)

                url = data.get('url', None)
                occurrences = data.get('occurrences', [])
            
                dados_processados.append({
                    'url': url,
                    'sharing_count': len(occurrences)
                })

            except json.JSONDecodeError:
                # Se uma linha não for um JSON válido, ela é ignorada
                print(f"Aviso: Linha com JSON inválido foi ignorada.")
                continue
            except Exception as e:
                # Captura outros erros inesperados na linha
                print(f"Ocorreu um erro ao processar uma linha: {e}")
                continue
except FileNotFoundError:
    print(f"ERRO: O arquivo '{file_path}' não foi encontrado.")
except Exception as e:
    # Captura outros erros inesperados (ex: arquivo corrompido)
    print(f"Ocorreu um erro geral: {e}")

Processando URLs: 0it [00:00, ?it/s]

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import random

df = pd.DataFrame(dados_processados)
media_compartilhamentos = df['sharing_count'].mean()
print("--- Estatísticas Gerais ---")
print(f"Média de compartilhamentos por vídeo: {media_compartilhamentos:.2f}")
limites_dos_bins = [-1, 0, 1, 5, 10, 50, 100, 500, 1000, 5000, 20000, np.inf]

nomes_dos_bins = [
    '0',
    '1',
    '2 a 5',
    '6 a 10',
    '11 a 50',
    '51 a 100',
    '101 a 500',
    '501 a 1.000',
    '1.001 a 5.000',
    '5.001 a 20.000',
    'Mais de 20.000'
]

df['faixa_compartilhamento'] = pd.cut(
    df['sharing_count'],
    bins=limites_dos_bins,
    labels=nomes_dos_bins
)

contagem_por_faixa = df['faixa_compartilhamento'].value_counts().sort_index()
print("\n--- Contagem de Vídeos por Faixa ---")
print(contagem_por_faixa)

--- Estatísticas Gerais ---
Média de compartilhamentos por vídeo: 4.75

--- Contagem de Vídeos por Faixa ---
faixa_compartilhamento
0                       0
1                 1441126
2 a 5              407160
6 a 10              39741
11 a 50             22688
51 a 100             3599
101 a 500            4816
501 a 1.000           823
1.001 a 5.000         678
5.001 a 20.000        137
Mais de 20.000         24
Name: count, dtype: int64

#### **1.2 View count per view**
___

In [13]:
import pandas as pd
import numpy as np

file_path = "data/youtube_titulos_saida.csv"

df = pd.read_csv(file_path)
display(df.head())

,video_id,title,description,channel_title,published_at,youtube_video_link,view_count,like_count,comment_count
0,jEKzQV5oajY,Free bus travel for migrants scrapped. For 5 m...,NaN,Joe Marsh,2024-04-10T15:05:37Z,https://www.youtube.com/watch?v=jEKzQV5oajY,1057.0,152.0,32.0
1,xrGGce8cmx8,What is Spiritual Warfare?,"This charge I commit unto thee, son Timothy, a...",WWURD,2023-10-18T14:39:18Z,https://www.youtube.com/watch?v=xrGGce8cmx8,65.0,6.0,1.0
2,uaozGpSc4nc,80 Putins Have Layers,"In February 2024, Tucker Carlson stood in fron...",The Mosaic Ark,2024-02-22T07:30:05Z,https://www.youtube.com/watch?v=uaozGpSc4nc,330.0,8.0,6.0
3,TwACgO_oPq4,Anacondaz — Акуле плевать (Official Music Video),#Anacondaz #Акулеплевать #Безпаники\n\nLong St...,ANACONDAZ,2014-05-20T09:29:45Z,https://www.youtube.com/watch?v=TwACgO_oPq4,2321870.0,24565.0,561.0
4,A59ftbhsQUE,𝐆𝐀𝐋𝐀𝐂𝐓𝐈𝐂 𝐀𝐋𝐋𝐈𝐀𝐍𝐂𝐄 𝐌𝐄𝐒𝐒𝐀𝐆𝐄|𝐁𝐈𝐆 𝐍𝐄𝐖𝐒!~𝐑𝐄𝐌𝐀𝐈𝐍 𝐀𝐋𝐄...,#pleiadians #5dimension #ashtar\n#pleiadians #...,GALACTIC ALLIANCE,2024-10-27T04:30:04Z,https://www.youtube.com/watch?v=A59ftbhsQUE,806.0,136.0,18.0

In [14]:
media_views = df['view_count'].mean()
mediana_views = df['view_count'].median()
desvio_views = df['view_count'].std()
min_views = df['view_count'].min()
max_views = df['view_count'].max()
q1 = df['view_count'].quantile(0.25)
q3 = df['view_count'].quantile(0.75)
iqr = q3 - q1  # Intervalo interquartil

print(f"Média de visualizações: {media_views:,.2f}")
print(f"Mediana de visualizações: {mediana_views:,.2f}")
print(f"Desvio padrão: {desvio_views:,.2f}")
print(f"Valor mínimo: {min_views:,.0f}")
print(f"1º quartil (Q1): {q1:,.0f}")
print(f"3º quartil (Q3): {q3:,.0f}")
print(f"Intervalo interquartil (IQR): {iqr:,.0f}")
print(f"Valor máximo: {max_views:,.0f}")

Média de visualizações: 2,558,331.78
Mediana de visualizações: 26,585.00
Desvio padrão: 43,834,525.69
Valor mínimo: 0
1º quartil (Q1): 3,178
3º quartil (Q3): 201,888
Intervalo interquartil (IQR): 198,710
Valor máximo: 16,246,886,449

In [16]:
max_index = df['view_count'].idxmax()
linha_max = df.loc[max_index]
print(linha_max)

(900178, 16246886449.0)
video_id                                                    XqZsoesa55w
title                 Baby Shark Dance | #babyshark Most Viewed Vide...
description           👇 Subscribe and watch new videos uploaded ever...
channel_title               Baby Shark - Pinkfong Kids’ Songs & Stories
published_at                                       2016-06-17T23:00:30Z
youtube_video_link          https://www.youtube.com/watch?v=XqZsoesa55w
view_count                                                16246886449.0
like_count                                                   45877196.0
comment_count                                                       NaN
Name: 900178, dtype: object

In [8]:
df.describe()

         view_count    like_count  comment_count
count  1.181141e+06  1.161309e+06   1.146705e+06
mean   2.558332e+06  3.437638e+04   1.661520e+03
std    4.383453e+07  3.219617e+05   2.645512e+04
min    0.000000e+00  0.000000e+00   0.000000e+00
25%    3.178000e+03  1.300000e+02   1.400000e+01
50%    2.658500e+04  1.091000e+03   1.160000e+02
75%    2.018880e+05  6.641000e+03   6.610000e+02
max    1.624689e+10  5.524703e+07   1.594942e+07

In [9]:
limites_dos_bins = [-1, 100000, 500000, 1000000, 2000000, 5000000, 10000000, np.inf]

nomes_dos_bins = [
    '0 a 100000',
    '100001 a 500000',
    '500001 a 1000000',
    '1000001 a 2000000',
    '2000001 a 5000000',
    '5000001 a 10000000',
    'Mais de 10000000'
]

df['faixa_views'] = pd.cut(
    df['view_count'],
    bins=limites_dos_bins,
    labels=nomes_dos_bins
)

contagem_por_faixa = df['faixa_views'].value_counts().sort_index()
print("\n--- Contagem de views por Faixa ---")
print(contagem_por_faixa)

--- Contagem de views por Faixa ---
faixa_views
0 a 100000            790392
100001 a 500000       192364
500001 a 1000000       55995
1000001 a 2000000      43328
2000001 a 5000000      42505
5000001 a 10000000     22080
Mais de 10000000       34477
Name: count, dtype: int64

In [17]:
media_views = df['like_count'].mean()
mediana_views = df['like_count'].median()
desvio_views = df['like_count'].std()
min_views = df['like_count'].min()
max_views = df['like_count'].max()
q1 = df['like_count'].quantile(0.25)
q3 = df['like_count'].quantile(0.75)
iqr = q3 - q1  # Intervalo interquartil

print(f"Média de likes: {media_views:,.2f}")
print(f"Mediana de likes: {mediana_views:,.2f}")
print(f"Desvio padrão: {desvio_views:,.2f}")
print(f"Valor mínimo: {min_views:,.0f}")
print(f"1º quartil (Q1): {q1:,.0f}")
print(f"3º quartil (Q3): {q3:,.0f}")
print(f"Intervalo interquartil (IQR): {iqr:,.0f}")
print(f"Valor máximo: {max_views:,.0f}")

Média de likes: 34,376.38
Mediana de likes: 1,091.00
Desvio padrão: 321,961.72
Valor mínimo: 0
1º quartil (Q1): 130
3º quartil (Q3): 6,641
Intervalo interquartil (IQR): 6,511
Valor máximo: 55,247,027

In [19]:
max_index = df['like_count'].idxmax()
linha_max = df.loc[max_index]
print(linha_max)

video_id                                                    kJQP7kiw5Fk
title                           Luis Fonsi - Despacito ft. Daddy Yankee
description           “Despacito” disponible ya en todas las platafo...
channel_title                                             LuisFonsiVEVO
published_at                                       2017-01-13T05:00:02Z
youtube_video_link          https://www.youtube.com/watch?v=kJQP7kiw5Fk
view_count                                                 8813261136.0
like_count                                                   55247027.0
comment_count                                                 4319159.0
Name: 959862, dtype: object

In [10]:
limites_dos_bins = [-1, 50, 100, 500, 1000, 5000, 10000, 50000, 100000, 500000, 1000000, 2000000, 5000000, 10000000, np.inf]

nomes_dos_bins = [
    '0 a 50',
    '51 a 100',
    '101 a 500',
    '501 a 1000',
    '1001 a 5000',
    '5001 a 10000',
    '10001 a 50000',
    '50001 a 100000',
    '100001 a 500000',
    '500001 a 1000000',
    '1000001 a 2000000',
    '2000001 a 5000000',
    '5000001 a 10000000',
    'Mais de 10000000'
]

df['faixa_likes'] = pd.cut(
    df['like_count'],
    bins=limites_dos_bins,
    labels=nomes_dos_bins
)

contagem_por_faixa = df['faixa_likes'].value_counts().sort_index()
print("\n--- Contagem de likes por Faixa ---")
print(contagem_por_faixa)

--- Contagem de likes por Faixa ---
faixa_likes
0 a 50                197597
51 a 100               65341
101 a 500             196987
501 a 1000            106486
1001 a 5000           263267
5001 a 10000           96843
10001 a 50000         146826
50001 a 100000         33850
100001 a 500000        40154
500001 a 1000000        7258
1000001 a 2000000       3700
2000001 a 5000000       2212
5000001 a 10000000       571
Mais de 10000000         217
Name: count, dtype: int64

In [11]:
contagem_nulos = df.isnull().sum()

print("--- Contagem de Linhas Nulas por Coluna ---")
print(contagem_nulos)

--- Contagem de Linhas Nulas por Coluna ---
video_id                   0
title                      1
description           107752
channel_title             12
published_at               0
youtube_video_link         0
view_count              2675
like_count             22507
comment_count          37111
faixa_views             2675
faixa_likes            22507
dtype: int64

### **2. How many groups one videos is shared**
___

In [28]:
import pandas as pd
import gzip
import json
from tqdm.notebook import tqdm

dados_processados = []
i =0
try:
    with open(file_path, "rt", encoding="utf-8") as f:
        for line in tqdm(f, desc="Processando URLs"):
            try:
                data = json.loads(line)

                url = data.get('url', None)
                occurrences = data.get('occurrences', [])

                # Obter todos os grupos únicos
                unique_groups = set([occ['folder'] for occ in occurrences])
                num_unique_groups = len(unique_groups)
            
                dados_processados.append({
                    'url': url,
                    'unique_group_count': num_unique_groups
                })
                
            except json.JSONDecodeError:
                # Se uma linha não for um JSON válido, ela é ignorada
                print(f"Aviso: Linha com JSON inválido foi ignorada.")
                continue
            except Exception as e:
                # Captura outros erros inesperados na linha
                print(f"Ocorreu um erro ao processar uma linha: {e}")
                continue
except FileNotFoundError:
    print(f"ERRO: O arquivo '{file_path}' não foi encontrado.")
except Exception as e:
    # Captura outros erros inesperados (ex: arquivo corrompido)
    print(f"Ocorreu um erro geral: {e}")

Processando URLs: 0it [00:00, ?it/s]

In [31]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import random

df = pd.DataFrame(dados_processados)
media_compartilhamentos = df['unique_group_count'].mean()
print("--- Estatísticas Gerais ---")
print(f"Média de compartilhamentos por vídeo: {media_compartilhamentos:.2f}")
limites_dos_bins = [-1, 0, 1, 5, 10, 50, 100, 500, 1000, 5000, 20000, np.inf]

nomes_dos_bins = [
    '0',
    '1',
    '2 a 5',
    '6 a 10',
    '11 a 50',
    '51 a 100',
    '101 a 500',
    '501 a 1.000',
    '1.001 a 5.000',
    '5.001 a 20.000',
    'Mais de 20.000'
]

df['faixa_compartilhamento'] = pd.cut(
    df['unique_group_count'],
    bins=limites_dos_bins,
    labels=nomes_dos_bins
)

contagem_por_faixa = df['faixa_compartilhamento'].value_counts().sort_index()
print("\n--- Contagem de Vídeos por Faixa ---")
print(contagem_por_faixa)

--- Estatísticas Gerais ---
Média de compartilhamentos por vídeo: 1.78

--- Contagem de Vídeos por Faixa ---
faixa_compartilhamento
0                       0
1                 1511845
2 a 5              359606
6 a 10              29451
11 a 50             14980
51 a 100             3505
101 a 500            1402
501 a 1.000             3
1.001 a 5.000           0
5.001 a 20.000          0
Mais de 20.000          0
Name: count, dtype: int64