# <center>Title Topic Modeling</center>
---

In [1]:
import pandas as pd
import nltk
import os
import sys
from nltk.corpus import stopwords
nltk.download('stopwords')

project_root_path = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root_path not in sys.path:
    sys.path.append(project_root_path)
from PreProcessing.pre_processing import PreProcessing
import numpy as np
import spacy as sp

[nltk_data] Downloading package stopwords to /home/ester/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Getting the English titles

In [2]:
df_clean = pd.read_csv("../data/preprocessed_english_titles.csv")
display(df_clean)

,Unnamed: 0,video_id,title,description,title_description,lang,clean_text
0,0,jEKzQV5oajY,Free bus travel for migrants scrapped. For 5 m...,NaN,Free bus travel for migrants scrapped. For 5 m...,en,free travel migrant scrap minute
1,1,xrGGce8cmx8,What is Spiritual Warfare?,"This charge I commit unto thee, son Timothy, a...",What is Spiritual Warfare? This charge I commi...,en,spiritual warfare charge commit unto thee timo...
2,2,uaozGpSc4nc,80 Putins Have Layers,"In February 2024, Tucker Carlson stood in fron...","80 Putins Have Layers In February 2024, Tucker...",en,putin layer february tucker carlson stand onio...
3,3,A59ftbhsQUE,𝐆𝐀𝐋𝐀𝐂𝐓𝐈𝐂 𝐀𝐋𝐋𝐈𝐀𝐍𝐂𝐄 𝐌𝐄𝐒𝐒𝐀𝐆𝐄|𝐁𝐈𝐆 𝐍𝐄𝐖𝐒!~𝐑𝐄𝐌𝐀𝐈𝐍 𝐀𝐋𝐄...,#pleiadians #5dimension #ashtar\n#pleiadians #...,𝐆𝐀𝐋𝐀𝐂𝐓𝐈𝐂 𝐀𝐋𝐋𝐈𝐀𝐍𝐂𝐄 𝐌𝐄𝐒𝐒𝐀𝐆𝐄|𝐁𝐈𝐆 𝐍𝐄𝐖𝐒!~𝐑𝐄𝐌𝐀𝐈𝐍 𝐀𝐋𝐄...,en,GALACTIC ALLIANCE MESSAGE NEWS REMAIN ALERT PR...
4,4,AKU0RokegSo,Los Angeles rain: Studio City homes evacuated ...,An atmospheric river storm has caused mudslide...,Los Angeles rain: Studio City homes evacuated ...,en,angeles rain studio city home evacuate mudslid...
...,...,...,...,...,...,...,...
686621,686621,xV2G3GFf2ug,Did you know this ? #gaza #god #israel #jesus ...,Have you seen this ? \n\nFULL VIDEO: Aries int...,Did you know this ? #gaza #god #israel #jesus ...,en,know gaza israel jesus bible palestine christ ...
686622,686622,GEhEUy85PsY,Meet the balkans,This is a video,Meet the balkans This is a video,en,meet balkan video
686623,686623,fNTfEPLoAik,Former Clark County sheriff arrested on 15 fel...,Former Clark County sheriff arrested on 15 fel...,Former Clark County sheriff arrested on 15 fel...,en,clark county sheriff arrest felony count clark...
686624,686624,8pEHwRiJVJM,What’s your thougts? #Bible #god #Christianscr...,What’s your thoughts?\n\nFULL VIDEO: 👇🏽\nhttps...,What’s your thougts? #Bible #god #Christianscr...,en,thougts bible christianscripture jesus biblica...
686625,686625,L_y36luTTok,Did you know this ? #gaza #god #israel #jesus ...,Have you seen this ? \n\nFULL VIDEO: Aries int...,Did you know this ? #gaza #god #israel #jesus ...,en,know gaza israel jesus bible palestine christ ...

In [3]:
df_teste = df_clean.sample(n=200000, random_state=42)
display(df_teste)
df_teste.to_csv("../data/df_teste.csv")

,Unnamed: 0,video_id,title,description,title_description,lang,clean_text
330540,330540,CMg-Ql0Dv1Q,Timcast IRL - Everyone Is Waiting On The Epste...,#shorts \nBUY OUR NEW SONG To Say FU To Woke M...,Timcast IRL - Everyone Is Waiting On The Epste...,en,timcast wait epstein docs release short short ...
557083,557083,50Y5r9HeR2w,Secret 10-Year Mission to an Alien Planet 40 L...,Special thanks to Established Titles! If you h...,Secret 10-Year Mission to an Alien Planet 40 L...,en,secret year mission alien planet light year aw...
517230,517230,FQIqfH2kFIg,Ohio Gov. Mike DeWine addresses false claims a...,"Ohio Gov. Mike DeWine, a Republican, addresses...",Ohio Gov. Mike DeWine addresses false claims a...,en,ohio mike dewine address false claim haitian i...
159348,159348,XsSq0lGyG_A,Tartaria - THUG LIFE 😎 #shorts |4|,"#tartaria #thuglife \n""Tartaria"" is likely a ...",Tartaria - THUG LIFE 😎 #shorts |4| #tartaria ...,en,tartaria thug life short tartaria thuglife tar...
164159,164159,JqOIKRF13lk,SECRET Migrant Cross. Eagle Pass Texas. Border...,I am reporting from Eagle Pass Texas covering ...,SECRET Migrant Cross. Eagle Pass Texas. Border...,en,secret migrant cross eagle pass texas border c...
...,...,...,...,...,...,...,...
164186,164186,nXFEFu0wmNE,Georgia's president vetoes media law that's pr...,President Salome Zourabichvili on Saturday vet...,Georgia's president vetoes media law that's pr...,en,georgia president veto medium provoke week pro...
447027,447027,H_UfyxPRhpU,The Thunder Rolls (Radio Edit),Provided to YouTube by Universal Music Group\n...,The Thunder Rolls (Radio Edit) Provided to You...,en,thunder roll radio edit provide youtube univer...
318782,318782,pdiVf68U0-s,The Bowlerhat Farmer: Solution to the FOOD ind...,NaN,The Bowlerhat Farmer: Solution to the FOOD ind...,en,bowlerhat farmer solution food industry year s...
216913,216913,HG9NavF_O6o,Congressman Spills The Tea on AIPAC,U.S. Representative Thomas Massie spilled the ...,Congressman Spills The Tea on AIPAC U.S. Repre...,en,congressman spill aipac representative thomas ...
104058,104058,k1SE25mURhc,Ellora Caves Documentary 2019 The Mind-Bogglin...,Everyone is trying to understand how the Ellor...,Ellora Caves Documentary 2019 The Mind-Bogglin...,en,ellora caves documentary mind boggle rock temp...

In [ ]:
from topicmodeling import run_topic_modeling

# Executa o BERTopic, definindo os parâmentros e usando o kmeans
#if run_topic_modeling(): print("Modelagem concluída.")
loaded_model, probs, topics = run_topic_modeling()

/home/ester/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
topicos = [t for t in loaded_model.get_topics().keys() if t != -1]
fig = loaded_model.visualize_barchart(topics=topicos, n_words=10)
fig.update_layout(title_text="",  height=110 +60 * len(topicos),
    margin=dict(l=120, r=20, t=30, b=20))
fig.show()

In [ ]:
a = loaded_model.get_topic_info()
a

,Topic,Count,Name,Representation,Representative_Docs
0,-1,3604,-1_dinar_iraqi_video_music,"[dinar, iraqi, video, music, channel, world, u...",[plantation mind james tunney james tunney iri...
1,0,1686,0_usdt_crypto_airdrop_earn,"[usdt, crypto, airdrop, earn, tarot, bitcoin, ...",[find earn month want upgrade dream home retir...
2,1,1636,1_news_trump_newsmax_ukraine,"[news, trump, newsmax, ukraine, watch, preside...",[expose entire invasion start finish redact cl...
3,2,1260,2_israel_bible_jesus_gaza,"[israel, bible, jesus, gaza, christ, hamas, is...",[iran reportedly order direct strike israel ne...
4,3,938,3_music_composer_auto_generate,"[music, composer, auto, generate, lyric, youtu...",[diamond head suck love remastered official au...
5,4,320,4_earth_flat_weather_ancient,"[earth, flat, weather, ancient, hurricane, sto...",[mammatus cloud victoria australia february sh...
6,5,221,5_trailer_defence_indian_movie,"[trailer, defence, indian, movie, game, film, ...",[green beret shootout ambush tongo tongo real ...
7,6,191,6_taiwanplus_china_taiwan_chinese,"[taiwanplus, china, taiwan, chinese, taiwanplu...",[hualien earthquake aftermath taiwanplus news ...
8,7,85,7_ireland_dublin_irish_gaelic,"[ireland, dublin, irish, gaelic, celtic, king,...",[myth gaelic history myth gaelic history video...
9,8,55,8_brew_serge_cast_podcast,"[brew, serge, cast, podcast, coffee, timcast, ...",[timcast michael cohen willing affect personal...