In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("../data/youtube_titulos_saida.csv")
display(df1)

,video_id,title,description,channel_title,published_at,youtube_video_link,view_count,like_count,comment_count
0,jEKzQV5oajY,Free bus travel for migrants scrapped. For 5 m...,NaN,Joe Marsh,2024-04-10T15:05:37Z,https://www.youtube.com/watch?v=jEKzQV5oajY,1057.0,152.0,32.0
1,xrGGce8cmx8,What is Spiritual Warfare?,"This charge I commit unto thee, son Timothy, a...",WWURD,2023-10-18T14:39:18Z,https://www.youtube.com/watch?v=xrGGce8cmx8,65.0,6.0,1.0
2,uaozGpSc4nc,80 Putins Have Layers,"In February 2024, Tucker Carlson stood in fron...",The Mosaic Ark,2024-02-22T07:30:05Z,https://www.youtube.com/watch?v=uaozGpSc4nc,330.0,8.0,6.0
3,TwACgO_oPq4,Anacondaz — Акуле плевать (Official Music Video),#Anacondaz #Акулеплевать #Безпаники\n\nLong St...,ANACONDAZ,2014-05-20T09:29:45Z,https://www.youtube.com/watch?v=TwACgO_oPq4,2321870.0,24565.0,561.0
4,A59ftbhsQUE,𝐆𝐀𝐋𝐀𝐂𝐓𝐈𝐂 𝐀𝐋𝐋𝐈𝐀𝐍𝐂𝐄 𝐌𝐄𝐒𝐒𝐀𝐆𝐄|𝐁𝐈𝐆 𝐍𝐄𝐖𝐒!~𝐑𝐄𝐌𝐀𝐈𝐍 𝐀𝐋𝐄...,#pleiadians #5dimension #ashtar\n#pleiadians #...,GALACTIC ALLIANCE,2024-10-27T04:30:04Z,https://www.youtube.com/watch?v=A59ftbhsQUE,806.0,136.0,18.0
...,...,...,...,...,...,...,...,...,...
1183811,J2FGKFv_xbs,Ministra de Relações Exteriores da África do S...,"""Os agentes israelenses tentam intimidar, mas ...",Williamsaje,2024-02-10T15:15:02Z,https://www.youtube.com/watch?v=J2FGKFv_xbs,74.0,12.0,2.0
1183812,fNTfEPLoAik,Former Clark County sheriff arrested on 15 fel...,Former Clark County sheriff arrested on 15 fel...,WLKY News Louisville,2023-11-09T09:24:16Z,https://www.youtube.com/watch?v=fNTfEPLoAik,358.0,5.0,NaN
1183813,8pEHwRiJVJM,What’s your thougts? #Bible #god #Christianscr...,What’s your thoughts?\n\nFULL VIDEO: 👇🏽\nhttps...,Aries Entertainment Podcast,2024-09-17T12:16:37Z,https://www.youtube.com/watch?v=8pEHwRiJVJM,1795796.0,74119.0,3230.0
1183814,L_y36luTTok,Did you know this ? #gaza #god #israel #jesus ...,Have you seen this ? \n\nFULL VIDEO: Aries int...,Aries Entertainment Podcast,2024-04-16T17:24:53Z,https://www.youtube.com/watch?v=L_y36luTTok,141201.0,7584.0,1391.0
1183815,cCx0cYP_QEs,دانشمندان ایران باستان؛ قسمت دوم (هخامنشیان، ا...,NaN,Kaveh Iranfarreh کاوه ایران‌فرّه,2024-08-25T13:47:31Z,https://www.youtube.com/watch?v=cCx0cYP_QEs,787.0,24.0,12.0

In [4]:
df2 = pd.read_csv("../data/preprocessed_english_titles.csv")
display(df2)

,Unnamed: 0,video_id,title,description,title_description,lang,clean_text
0,0,jEKzQV5oajY,Free bus travel for migrants scrapped. For 5 m...,NaN,Free bus travel for migrants scrapped. For 5 m...,en,free travel migrant scrap minute
1,1,xrGGce8cmx8,What is Spiritual Warfare?,"This charge I commit unto thee, son Timothy, a...",What is Spiritual Warfare? This charge I commi...,en,spiritual warfare charge commit unto thee timo...
2,2,uaozGpSc4nc,80 Putins Have Layers,"In February 2024, Tucker Carlson stood in fron...","80 Putins Have Layers In February 2024, Tucker...",en,putin layer february tucker carlson stand onio...
3,3,A59ftbhsQUE,𝐆𝐀𝐋𝐀𝐂𝐓𝐈𝐂 𝐀𝐋𝐋𝐈𝐀𝐍𝐂𝐄 𝐌𝐄𝐒𝐒𝐀𝐆𝐄|𝐁𝐈𝐆 𝐍𝐄𝐖𝐒!~𝐑𝐄𝐌𝐀𝐈𝐍 𝐀𝐋𝐄...,#pleiadians #5dimension #ashtar\n#pleiadians #...,𝐆𝐀𝐋𝐀𝐂𝐓𝐈𝐂 𝐀𝐋𝐋𝐈𝐀𝐍𝐂𝐄 𝐌𝐄𝐒𝐒𝐀𝐆𝐄|𝐁𝐈𝐆 𝐍𝐄𝐖𝐒!~𝐑𝐄𝐌𝐀𝐈𝐍 𝐀𝐋𝐄...,en,GALACTIC ALLIANCE MESSAGE NEWS REMAIN ALERT PR...
4,4,AKU0RokegSo,Los Angeles rain: Studio City homes evacuated ...,An atmospheric river storm has caused mudslide...,Los Angeles rain: Studio City homes evacuated ...,en,angeles rain studio city home evacuate mudslid...
...,...,...,...,...,...,...,...
686621,686621,xV2G3GFf2ug,Did you know this ? #gaza #god #israel #jesus ...,Have you seen this ? \n\nFULL VIDEO: Aries int...,Did you know this ? #gaza #god #israel #jesus ...,en,know gaza israel jesus bible palestine christ ...
686622,686622,GEhEUy85PsY,Meet the balkans,This is a video,Meet the balkans This is a video,en,meet balkan video
686623,686623,fNTfEPLoAik,Former Clark County sheriff arrested on 15 fel...,Former Clark County sheriff arrested on 15 fel...,Former Clark County sheriff arrested on 15 fel...,en,clark county sheriff arrest felony count clark...
686624,686624,8pEHwRiJVJM,What’s your thougts? #Bible #god #Christianscr...,What’s your thoughts?\n\nFULL VIDEO: 👇🏽\nhttps...,What’s your thougts? #Bible #god #Christianscr...,en,thougts bible christianscripture jesus biblica...
686625,686625,L_y36luTTok,Did you know this ? #gaza #god #israel #jesus ...,Have you seen this ? \n\nFULL VIDEO: Aries int...,Did you know this ? #gaza #god #israel #jesus ...,en,know gaza israel jesus bible palestine christ ...

In [5]:
print("\nJuntando os DataFrames para encontrar os vídeos em comum...")
merged_df = pd.merge(df1, df2, on='video_id', how='inner')
print(f"Encontrados {len(merged_df)} vídeos em comum.")

print("Selecionando e renomeando as colunas desejadas...")

colunas_originais = [
    'video_id',
    'view_count',
    'like_count',
    'comment_count'
]

try:
    final_df = merged_df[colunas_originais].copy() 
except KeyError as e:
    print(f"\nERRO: Uma das colunas não foi encontrada no DataFrame! Detalhe: {e}")
    print("Verifique se os nomes em 'colunas_originais' estão corretos.")
    exit()


display(final_df)

final_df.to_csv("../data/df_analise", index=False)

Juntando os DataFrames para encontrar os vídeos em comum...
Encontrados 686626 vídeos em comum.
Selecionando e renomeando as colunas desejadas...

           video_id  view_count  like_count  comment_count
0       jEKzQV5oajY      1057.0       152.0           32.0
1       xrGGce8cmx8        65.0         6.0            1.0
2       uaozGpSc4nc       330.0         8.0            6.0
3       A59ftbhsQUE       806.0       136.0           18.0
4       AKU0RokegSo     60863.0       406.0          152.0
...             ...         ...         ...            ...
686621  xV2G3GFf2ug   2738551.0     67765.0         5049.0
686622  GEhEUy85PsY   7617763.0    210152.0        14042.0
686623  fNTfEPLoAik       358.0         5.0            NaN
686624  8pEHwRiJVJM   1795796.0     74119.0         3230.0
686625  L_y36luTTok    141201.0      7584.0         1391.0

[686626 rows x 4 columns]