In [2]:
import pandas as pd

In [3]:
path = "data/macrotopics_pred.csv"
df_all = pd.read_csv(path)
df_all.head()

,video_id,text,channel_title,published_at,view_count,like_count,comment_count,occurrences,toxicity,severe_toxicity,...,perspective_insult,perspective_severe_toxicity,perspective_obscene,perspective_toxicity,perspective_identity_attack,perspective_threat,macrotopic_pred,macrotopic_prob,lifetime,send_count
0,jEKzQV5oajY,travel migrant scrap minute,Joe Marsh,2024-04-10T15:05:37Z,1057.0,152.0,32.0,"[{'id': 1416, 'folder': 'channel_1556142220', ...",0.000659,0.000117,...,0.206683,0.021936,0.138744,0.360951,0.367026,0.038566,Others,0.000000,1.0,1
1,xrGGce8cmx8,spiritual warfare charge commit unto thee timo...,WWURD,2023-10-18T14:39:18Z,65.0,6.0,1.0,"[{'id': 60799, 'folder': 'channel_1466271872',...",0.295000,0.001137,...,0.021224,0.005379,0.008414,0.123468,0.049762,0.029415,Religion,0.000000,1.0,1
2,uaozGpSc4nc,putin layer february tucker carlson stand onio...,The Mosaic Ark,2024-02-22T07:30:05Z,330.0,8.0,6.0,"[{'id': 40486, 'folder': 'channel_1235978663',...",0.001735,0.000102,...,0.132458,0.010376,0.003292,0.229804,0.062040,0.033386,Others,0.021935,1.0,4
3,A59ftbhsQUE,GALACTIC ALLIANCE MESSAGE NEWS REMAIN ALERT PR...,GALACTIC ALLIANCE,2024-10-27T04:30:04Z,806.0,136.0,18.0,"[{'id': 449843, 'folder': 'channel_1571505334'...",0.002710,0.000104,...,0.019419,0.005112,0.001093,0.075294,0.017666,0.022509,Religion,0.005000,2.0,5
4,AKU0RokegSo,angeles rain studio city evacuate mudslide atm...,FOX 11 Los Angeles,2024-02-06T01:45:29Z,60863.0,406.0,152.0,"[{'id': 104116, 'folder': 'channel_1438734111'...",0.001515,0.000100,...,0.027841,0.004921,0.002368,0.111507,0.019375,0.028207,Environment,0.000000,2.0,2

In [4]:
df_all["macrotopic_pred"].value_counts()

macrotopic_pred
Others                         245627
Religion                       111071
Entertainment                  110640
American Politics               52998
War                             52846
Foreign Policy                  40410
Hobbies                         18913
Health                          11522
Environment                     11500
Crime, Security and Justice      9341
Technology                       8719
Name: count, dtype: int64

In [8]:
df_saude = df_all[df_all["macrotopic_pred"] == "Health"]
for index, row in df_saude.iterrows():
    print("youtu.be/"+row["video_id"])

youtu.be/N8pOOUtlWWw
youtu.be/gVn_-56sgIM
youtu.be/V05WiACDI3Y
youtu.be/4bpS3VVrKO0
youtu.be/JpFLlnfjHHE
youtu.be/Q3e2OQHSnns
youtu.be/K2E5VWgjLuA
youtu.be/3wjZI2fE9Gk
youtu.be/mIEpXwu31Us
youtu.be/RqVHh3QKWlI
youtu.be/_3WDD654alw
youtu.be/83IMYEBfR54
youtu.be/Fk05haeKWqw
youtu.be/_mNTpwmR49Q
youtu.be/D0wlhb-MplM
youtu.be/4Mtw3vBQYOg
youtu.be/0r_gBPRubcg
youtu.be/gfikT_O4v9A
youtu.be/5N4GtxkCtlM
youtu.be/rkXiYAn22k8
youtu.be/oFtK-baOhCE
youtu.be/zMIHzJ6bGnU
youtu.be/6p8vq0aP4v0
youtu.be/9llgOuUN_JE
youtu.be/656dQCjvutw
youtu.be/_-IbjgHWRMQ
youtu.be/Or086JL4klo
youtu.be/4CAM9XFDpVI
youtu.be/oNRoko4aBi0
youtu.be/c-dvT0F-yks
youtu.be/CWPkGh1rzx0
youtu.be/LPfPUmhW8YQ
youtu.be/9VMl2S2JMWI
youtu.be/ovGAKEOzG1Y
youtu.be/ZpPEIXotGMs
youtu.be/mTCGmP_TzpY
youtu.be/GQWSqHZZu1Y
youtu.be/2Z4bcLsKGcQ
youtu.be/CNdcWITMhR8
youtu.be/xSukz1szSs8
youtu.be/igUDdBLRm-w
youtu.be/5YDyLbuJ19M
youtu.be/eQpNHZRKEYk
youtu.be/60Im7PQRA3Y
youtu.be/q3s601pzaK4
youtu.be/UiLGSVH_UPA
youtu.be/0W19chp7qUA
youtu.be/jK36jlB9gZE
youtu.be/5oXvYAmZVyU
youtu.be/KkgHrxdvQOA
youtu.be/afPWtWvULUY
youtu.be/M-skwhRFWe0
youtu.be/Ov8SnxBx640
youtu.be/Q7ZzUJEgAYc
youtu.be/n7KPI9oroSQ
youtu.be/FDKbBhZKw9w
youtu.be/Fk1on7-rGzk
youtu.be/YBqPvd_qYSc
youtu.be/z8dfLN5qpsI
youtu.be/-3W0TSgZmJM
youtu.be/2LwECMC178k
youtu.be/xoNljqhJiCo
youtu.be/Qor8_eB26Zw
youtu.be/E7s-BUsVWjg
youtu.be/KmffKx1HeKQ
youtu.be/zDotPUzhlYA
youtu.be/I0Jh3zP-DdM
youtu.be/B-vvNSFNKus
youtu.be/nbfgFyfHSMU
youtu.be/fdK-A01OUjs
youtu.be/lUdPP_7e7i0
youtu.be/nAS8lJ_66B4
youtu.be/aDTrCCfyR6A
youtu.be/HGl9e7tmkw8
youtu.be/BLLG1-vIGuo
youtu.be/N-4aU5ZesVY
youtu.be/HVs3Ak17jfg
youtu.be/Y40eaNIuVME
youtu.be/63qeqLA9V9Q
youtu.be/3qZX0KBseIc
youtu.be/6jxa6Vfqy3g
youtu.be/ZxbrFP_pZZk
youtu.be/wyXuPwsLGWI
youtu.be/D4oqvYuqLKQ
youtu.be/GJxGFVt-hmA
youtu.be/4SDxAFOQVXQ
youtu.be/g8S1dw47rAM
youtu.be/Ji4-2FYiE68
youtu.be/JIWjN6u93w4
youtu.be/-io8Ufsq67A
youtu.be/ZXFuQJgA3WY
youtu.be/YzRI4ywD01w
youtu.be/qOOuxPUStjg
youtu.be/2pn-1bwdYz0
youtu.be/e62vIOEfLXI
youtu.be/Bl5OngSFaHw
youtu.be/XEcssz8NOhg
youtu.be/_zfdf3voy2I
youtu.be/4PCY0V9hpfA
youtu.be/PzX_NS7EwF0
youtu.be/1vYZX-YK29M
youtu.be/8sKFcJkc6sg
youtu.be/m0pETcZ0-is
youtu.be/1xwaG-GBHIU
youtu.be/_q4S87Ptgwo
youtu.be/1TC1138rsWs
youtu.be/bOIVFanZsvc
youtu.be/js4vuuScWBE
youtu.be/6FzjhRW6qPY
youtu.be/cAmMpAR5hjY
youtu.be/AvN7dQg9SZE
youtu.be/pecpiTH-TlU
youtu.be/paIFO9g5TLw
youtu.be/y5cDu3sEyn0
youtu.be/AXq2ZdXXFCU
youtu.be/0G3JbbaGhqc
youtu.be/TdsQe4y5s1g
youtu.be/zVpj6C2_Rno
youtu.be/L-xwB0RGuFQ
youtu.be/l8Tq62c0kzk
youtu.be/8ExTddtinMQ
youtu.be/lDfSHmSAqfw
youtu.be/mPuKYbok6nk
youtu.be/gRnmzFB04x0
youtu.be/4vYR7KXHqo4
youtu.be/ntBNvGE7vbo
youtu.be/I38OwYmMB6I
youtu.be/gG4V-MIfMjI
youtu.be/WENozC2rrhk
youtu.be/ESOV9CGrtBI
youtu.be/hF-343AcOzM
youtu.be/gP3yK-Tvfao
youtu.be/pdN1E6OYxVU
youtu.be/yw6D98v0BBg
youtu.be/WgoixKhPaMY
youtu.be/gYOwDjWUkF8
youtu.be/Re7AUbpyoAU
youtu.be/hHH3ie5OM-w
youtu.be/Erarkc8ZjHs
youtu.be/Z26BvHOD_sg
youtu.be/_Li_4ISLB0c
youtu.be/xaKOURXhSNU
youtu.be/mg3uAYFee54
youtu.be/plpiRcVMbg0
youtu.be/TZTsqNTYOyE
youtu.be/mVAjuor_aDQ
youtu.be/tHsXMdyJCz0
youtu.be/NjpEeHtJeDg
youtu.be/OY36GKQQ9p8
youtu.be/arLNLXQoTck
youtu.be/paPVCrMkSUQ
youtu.be/Xl9zgDGko5U
youtu.be/QrcXClD01B4
youtu.be/Byhaw2k9PtM
youtu.be/6z95pV1FJVU
youtu.be/z4oSLajsHrY
youtu.be/wVbKiKchqjY
youtu.be/XxPLWR1U5D0
youtu.be/qqquqw92zRc
youtu.be/V4GEaDCY8No
youtu.be/kOzpoa-M5Mo
youtu.be/ilF4juaCpLY
youtu.be/-VPOOfu4xAE
youtu.be/3NUm8r5pylI
youtu.be/8z8cRh9owQE
youtu.be/LXv85pl3DfM
youtu.be/qvW3zpaXm_Y
youtu.be/sAKkjD3nEv0
youtu.be/LoQ48nyWPBM
youtu.be/sKV9rF7meko
youtu.be/ObCWPkQW-d0
youtu.be/YWfrJj901kc
youtu.be/lhrwWuD_Ggc
youtu.be/4RU7NDNEv8w
youtu.be/7cdSaZ8HDmg
youtu.be/ClqK7XvfLg0
youtu.be/2aqmcTDo550
youtu.be/1g1rSggnBv0
youtu.be/TU9DkMxcXuo
youtu.be/j-Qon21aj2w
youtu.be/qBdLSmBYUDc
youtu.be/AX4CJ0aYMWc
youtu.be/CgBoCxHwrRs
youtu.be/qcECDs0cusM
youtu.be/pZX8ikmWvEU
youtu.be/7Gk6F4KQwMg
youtu.be/YoWom0CCRKM
youtu.be/IJHY327sc5A
youtu.be/gHDNKn7VTPA
youtu.be/1PYeWr6sJVE
youtu.be/3Q_13qQxbSs
youtu.be/woTsaYabCZY
youtu.be/IKW9lHlLHXE
youtu.be/YoLqm8bSfyI
youtu.be/4Dr0qUTewlQ
youtu.be/4IamF0G-i-w
youtu.be/5BnknMowLEM
youtu.be/gNnYUHUJltI
youtu.be/f54Fr1Nidaw
youtu.be/oIRzVI5vdb8
youtu.be/03HGFfBaWiw
youtu.be/tsOEKvJFhck
youtu.be/6wo9L0991Hg
youtu.be/v5FZ-gjQ2nI
youtu.be/htxuJD2zQiI
youtu.be/wuq8H3llZuA
youtu.be/dtVI307usb4
youtu.be/jMYBQGLuQrI
youtu.be/5eF3gK9_398
youtu.be/JP30fncmFXs
youtu.be/DeHLNthYTSI
youtu.be/woO8fSQygkE
youtu.be/oUikS1CeyOQ
youtu.be/bBHBBNpWACs
youtu.be/canEZNMEJag
youtu.be/GsomcvdT7Po
youtu.be/o8-vlYFT09o
youtu.be/7l93DdrOogI
youtu.be/WBnWvx7or7Q
youtu.be/DmlxAVvOGiY
youtu.be/U8iV14N4RKE
youtu.be/bwdtfXWWd8k
youtu.be/a9_sX93RHOk
youtu.be/Eec98ie0Plg
youtu.be/8BtS0LIt_7E
youtu.be/LYCHHYFS3gA
youtu.be/VZW8hk5-auo
youtu.be/BQjeAMqCyds
youtu.be/-BZ5Th9PjmU
youtu.be/b1_KFfaekHU
youtu.be/f7HKYxbnThg
youtu.be/_kAnH5SQy34
youtu.be/hwERLnMz8wo
youtu.be/FVkMHCHaQd0
youtu.be/qqwURB1ngiA
youtu.be/-4idzawKj0s
youtu.be/rGu8php0XoY
youtu.be/VWdHZ-3u21Q
youtu.be/gmn6nQZBeSo
youtu.be/5iKAciilAM0
youtu.be/mQ8-saXsQ00
youtu.be/m56tLToiIhg
youtu.be/cukt_rhTdtU
youtu.be/mBKIsTuF3_s
youtu.be/cCSru3tgHL4
youtu.be/RU64CXe0TlI
youtu.be/skyd1JiJiYs
youtu.be/F30qB2tMQgQ
youtu.be/BzI016h61Tw
youtu.be/gkJQpVUTqDU
youtu.be/fUeT8dBG8G8
youtu.be/ngU__1z5uRA
youtu.be/qZ37pTp58qA
youtu.be/klBpxOWvOr0
youtu.be/Lbq3T3ZDvbQ
youtu.be/oz1lrlqdcvw
youtu.be/Qom_FPbt1YI
youtu.be/jkXXhofaGR8
youtu.be/1GB_MNIdg_k
youtu.be/r2JcmyEoKos
youtu.be/XblZS477PSs
youtu.be/OQrypayzdDw
youtu.be/gQs-CnMMYR4
youtu.be/9j6zl8rW3pg
youtu.be/b3Q9o3APTsQ
youtu.be/6QAFXFFAqVQ
youtu.be/yISlhpeMH1w
youtu.be/a5YB55XMNm8
youtu.be/I-YDUXLpdFg
youtu.be/5q8s-XrM-Z8
youtu.be/zO4cSPL572c
youtu.be/pIB3neebwSk
youtu.be/ck18VnpyARc
youtu.be/TEb33U0hHxM
youtu.be/zux7ry50IjQ
youtu.be/dMghM6TxiBk
youtu.be/hLkRZLUsEiI
youtu.be/zHdVFmjmQHM
youtu.be/YEfdEvU-uC0
youtu.be/Qgy_bZIiAJU
youtu.be/G-r9pII38M0
youtu.be/lbyuzaFNJX8
youtu.be/4MPH0QD74Yw
youtu.be/mSWeuHKnnmE
youtu.be/bKbtNAxCcaw
youtu.be/9MqZ4iUt6J4
youtu.be/cNdwjha-d0Q
youtu.be/PJ2jCDQMQ00
youtu.be/MibfMW_9yJU
youtu.be/kUsmtIOfqiU
youtu.be/VqcdOHudAWs
youtu.be/lRww4Bf684E
youtu.be/aWTHHgcBfiY
youtu.be/DmKIkxbk3TE
youtu.be/eP_-bNw3BQo
youtu.be/2nuzf0FxO94
youtu.be/kZn9vRvvvbw
youtu.be/efi9v86isSw
youtu.be/36tmeJ1NeWc
youtu.be/2a6MYX-do64
youtu.be/i0Bi9wlHybQ
youtu.be/e5yfP9hUaeQ
youtu.be/sDpalaTfKbk
youtu.be/mSqlEZKqlI8
youtu.be/wPytlDFqJBE
youtu.be/mUxIvrImh1Q
youtu.be/pGrdB1AeznU
youtu.be/hKBMI4IQDW4
youtu.be/-KMvOHU1mwM
youtu.be/0ZgbatFqtNA
youtu.be/pAfMJ6cHJ34
youtu.be/Ds0UFahTWjw
youtu.be/Vkm5PI9FLgc
youtu.be/UQfAKu6EesY
youtu.be/K9CXhIFPGI8
youtu.be/2TiKZFdrjNM
youtu.be/9405FgR2Kik
youtu.be/znLUzi_Ih0U
youtu.be/QnaY93L5SEg
youtu.be/WAS3uacjR_w
youtu.be/WJ7N_9UYK1Y
youtu.be/q1OxAxIuVNU
youtu.be/rTNoGXZq19A
youtu.be/b6VrBsRiUuc
youtu.be/_Y3zMukBetk
youtu.be/0BrLo04xQ8o
youtu.be/GU6Q2U-1crI
youtu.be/pdKgMQI_JoI
youtu.be/lbzNBHdKgdA
youtu.be/KYT2UoMk-oo
youtu.be/qj_QgFIqAdE
youtu.be/nVkNZDd_ESw
youtu.be/T7e-uC7lZ2E
youtu.be/VZHEX1FQg6M
youtu.be/qJbQUmDq31U
youtu.be/Y8XQNFyMe8M
youtu.be/j9r7ORs1k0E
youtu.be/m7x0nbOd5ok
youtu.be/6Z2BXk4EVaM
youtu.be/gRHozqev-tw
youtu.be/cMaHKykfdcQ
youtu.be/XNBDP2L1Vfo
youtu.be/NQffXjs3fUY
youtu.be/071rrm3Yvac
youtu.be/qSAy7j8t9fs
youtu.be/JPSCFY5CoKg
youtu.be/8CYUiI9t4_o
youtu.be/5_22IDq_36k
youtu.be/7Wzg6agYKAY
youtu.be/aN1eptTaWVM
youtu.be/o9Z5HbmFHKw
youtu.be/cpa7-yii6Yc
youtu.be/3mVUO1LiqE8
youtu.be/SxatfjW4gdA
youtu.be/3FxVN90mDcc
youtu.be/uR2ksqDy5os
youtu.be/04n2It2kQE0
youtu.be/YHp5K_ErOLA
youtu.be/fQ0_VAEniVM
youtu.be/uhXZjlp8E_k
youtu.be/O4sgxgd5Pdc
youtu.be/uHpN1FQ-Hvo
youtu.be/nfsZOmSYJoo
youtu.be/tpo_Iv4EN98
youtu.be/k9QiEDS6YWs
youtu.be/XlLxpsmgQ9Y
youtu.be/H_A4acIo8kY
youtu.be/yj_RRIJN0fc
youtu.be/9KYwYQ2n71s
youtu.be/GVXY0-FMJFg
youtu.be/6pJMa9QnVd0
youtu.be/hvPDFdf-6MY
youtu.be/rbeb0vKVQWA
youtu.be/zD1StTqrY3A
youtu.be/iBAjADAG8tU
youtu.be/qaW1n0HAi2w
youtu.be/b58a-O3LRsU
youtu.be/gOrJbqShcrg
youtu.be/fSb0Fti-2Lo
youtu.be/KZyP6MfpvHs
youtu.be/fnh3P8Kd_E4
youtu.be/Uj3myg6WYzA
youtu.be/xcPRVjpJrwE
youtu.be/enMn7I7BM8Q
youtu.be/NYFvm-YXN4o
youtu.be/fYkQO4WDZNg
youtu.be/FeDMBCZHqp4
youtu.be/pqkf3_sET5I
youtu.be/8mIP83ZW27Y
youtu.be/obx7cJtk3fE
youtu.be/bAM6JXaK2Gw
youtu.be/67Am1uOVVjI
youtu.be/sXH7OeuGr4c
youtu.be/CQOfH9VGMFI
youtu.be/RuYuEjud9lc
youtu.be/QDf0-tCDqn4
youtu.be/dWdLYF2bnKU
youtu.be/kYcS9v0d8Hk
youtu.be/BMBGGDdZ3QM
youtu.be/u8wLawglpTE
youtu.be/IyY83IBOOIk
youtu.be/9DfQHPaxEog
youtu.be/IOuyvTkAopA
youtu.be/w70ZAgar0qc
youtu.be/Re2j2C9n1ck
youtu.be/ubZvXkLHCwU
youtu.be/nN9GCEhi478
youtu.be/tWU3O3X5kKE
youtu.be/LeVFNJ6zbgY
youtu.be/J04_d7lUs6c
youtu.be/MKvzAfKszYc
youtu.be/Af4QenGgTyk
youtu.be/0Ur_FUwGEAM
youtu.be/b4CpC4uNOss
youtu.be/L0K8Wk0FLd8
youtu.be/uIn6HVNe8ZM
youtu.be/AsUmqF5A208
youtu.be/HfknEr2ctRI
youtu.be/Gxm62BODD8M
youtu.be/syqrp2kngNs
youtu.be/FgY126QX_w0
youtu.be/O8E8DWAlTfU
youtu.be/gzx9rS2b95Q
youtu.be/IMRTSwb3hCs
youtu.be/mToHUKRsxhg
youtu.be/eyXO0_GZ6t4
youtu.be/HzOczewkkdI
youtu.be/YIrejVKeMUI
youtu.be/3FhlTNpqa3s
youtu.be/GOy5Oq6Of8I
youtu.be/VkTk02u9enQ
youtu.be/y3dbAmEJzyU
youtu.be/l5dCvfbnqqA
youtu.be/2TiAqh6POG8
youtu.be/mwxPtvN6m0M
youtu.be/hZr3qn3PW6s
youtu.be/MVyfBjw5caI
youtu.be/4Fx-TDBUMxY
youtu.be/poVRv4KvaqE
youtu.be/t4FMBm7ljRM
youtu.be/2gKKHdubsrc
youtu.be/nlSXxR950Mw
youtu.be/xhUWEPs3NJ4
youtu.be/N9QD9Nf4YH8
youtu.be/LKq7NGqFZP0
youtu.be/nEMQzvibuFs
youtu.be/GhP_8t7uKnw
youtu.be/EHT4nQ2wgkA
youtu.be/k1LtlqICXII
youtu.be/LjWxk7-RCqI
youtu.be/n2Tg1Xe-JGo
youtu.be/kPZannhi8a4
youtu.be/qBF-i42ehYE
youtu.be/ICkVa0MBqiU
youtu.be/a37VQ92k1qk
youtu.be/Z4F8mterVGE
youtu.be/1uerS5JjjRI
youtu.be/UoF3Zt3ZZyo
youtu.be/ZyiRXHZwjFw
youtu.be/hrceVq-KXiA
youtu.be/z3_efl4t6uI
youtu.be/aNLfX86U3Fk
youtu.be/dp7HzK7j1IM
youtu.be/_BQ8ApUPdY0
youtu.be/dUrxrbEdDQs
youtu.be/Jrvv-3tsoek
youtu.be/UdrzISS-Npw
youtu.be/WhwwKl6t6Cw
youtu.be/kbL0q523KFM
youtu.be/7UFV-ydHGjI
youtu.be/DseWF6gdq24
youtu.be/IuJOueC7j2s
youtu.be/kAxSZgk3OPI
youtu.be/Hbeez2TSPI0
youtu.be/h63sGb4k3Ck
youtu.be/ue7picBWT4c
youtu.be/mtEr-rGGnbE
youtu.be/H0n6qXMS0n0
youtu.be/JMjC6Xa3MGA
youtu.be/Gm-7mcR86QU
youtu.be/axABUZg2Zw4
youtu.be/Zv8uA3Fcrd8
youtu.be/FUwbDWdVPKA
youtu.be/4TNatLEyFAo
youtu.be/pfgM6nfWU-I
youtu.be/2wuMkShZ42o
youtu.be/yNSCQyPv-7U
youtu.be/XVv32ezE4jM
youtu.be/hxY43mBVOOc
youtu.be/7M8040BLtrA
youtu.be/f6lNvQko-g4
youtu.be/bAYJJdJa3dw
youtu.be/mnUtM2pOh1I
youtu.be/gDt37xMLkLs
youtu.be/shzHpxYDlw0
youtu.be/Aaxa7rxEbyk
youtu.be/sDJF3S-Kiqk
youtu.be/tPGZx_-Ervk
youtu.be/ySdOZkz_ezU
youtu.be/palbTzUZtH4
youtu.be/VuAG7s9ogxA
youtu.be/SJkC0hhEjO4
youtu.be/cOtDfrSL2gM
youtu.be/ajol46vUTbs
youtu.be/vfLZOkn0chc
youtu.be/Q_ko5KqOTZI
youtu.be/VUQac3xOwGE
youtu.be/7CD2JxwsLk0
youtu.be/Qm06dgF3nNQ
youtu.be/z-wwaH_ukPo
youtu.be/w-MtX4ELrao
youtu.be/aM61uwjBQSA
youtu.be/0VPtftnxn5k
youtu.be/L4Ad8J-ItpI
youtu.be/IfBlM3HfHKs
youtu.be/qw5wJk5wOUM
youtu.be/aeDLiFppOrk
youtu.be/vzjWwhvEFUU
youtu.be/PDpP6x9dFxk
youtu.be/yQWi5wgODXE
youtu.be/iwsdIX0_qK4
youtu.be/ZOEWWvwCj_s
youtu.be/SLQ5rz9xCl4
youtu.be/ek6uPuHJVJI
youtu.be/3pwtnTPQUM8
youtu.be/0T25L5yl0oc
youtu.be/HDJLcWENF7E
youtu.be/30FXo5L0RQo
youtu.be/0d4_wzvzTP4
youtu.be/JIYpxLrNd-A
youtu.be/rJt-PYiu_-c
youtu.be/QX9wkZSXhFw
youtu.be/obEA3NFEW-I
youtu.be/U8gVXqlBF4k
youtu.be/4uBKMbv9u6I
youtu.be/wp5h-XWjrcU
youtu.be/jpnw_Qgv4r8
youtu.be/rpC43GX3UrU
youtu.be/cVKeLkKyJpU
youtu.be/fWSfGrh-gus
youtu.be/90jcnQuIR3k
youtu.be/aW6zToSbrZk
youtu.be/muWumarDa3c
youtu.be/Ns37XqoREak
youtu.be/27lVeD6rnBo
youtu.be/NaPmHYozrXE
youtu.be/m7StkvQ7kos
youtu.be/S7br7QqhkZE
youtu.be/TVCoQm5i9nI
youtu.be/HYILnjc_wuY
youtu.be/ZV91HpxR-v4
youtu.be/1egMi82eZew
youtu.be/ljQx2Zh4bkk
youtu.be/HVXEddUBxHM
youtu.be/MMdXZV41jM0
youtu.be/rsha-Ui2Cww
youtu.be/zX9bU_ALyOs
youtu.be/Tdc9o4hFFYw
youtu.be/HhHJ51FJC2w
youtu.be/Vy5OkKIgk28
youtu.be/p8dp_ixoblQ
youtu.be/8qeZfTaaUXw
youtu.be/aaF2WCH8fAo
youtu.be/y430Uc8JtuM
youtu.be/FuIUDh-DtQ4
youtu.be/2nzcrGHjuaU
youtu.be/2OY1JJXAFW8
youtu.be/oW-S-jDG3Z0
youtu.be/IahfmrAwfGg
youtu.be/wF3KwUWOo7M
youtu.be/LSqiJozPpF0
youtu.be/Uq6cUHH4K1k
youtu.be/uBqNYt6oGCc
youtu.be/kDpPx0wozhU
youtu.be/2jZbnpVt-KY
youtu.be/VCv_0fz_xxw
youtu.be/7N-1O_uqxGI
youtu.be/MwDh3IEXYcU
youtu.be/CAN-Un51uqM
youtu.be/dFTbrjIf14c
youtu.be/4dDYwOxgvAs
youtu.be/vnTTiy0ZVVo
youtu.be/9KSZIjUDr70
youtu.be/vXuu_8OKUvY
youtu.be/ZnkQSjKwH-M
youtu.be/abIVZ_l-D6Y
youtu.be/qpb_tJN1wxs
youtu.be/kjnGbHqwLME
youtu.be/VaVC3PAWqLk
youtu.be/mfEj7BsWR7A
youtu.be/XGP9vQDqhno
youtu.be/BD10p2-5HCA
youtu.be/HnagHwovBfo
youtu.be/J7JjzQ3U86A
youtu.be/oP1EEWjErDw
youtu.be/5xbwQ6tPT4Y
youtu.be/7OVN4GBGQVM
youtu.be/fC90quQ6oz8
youtu.be/0dyHiX6fRQ4
youtu.be/CsYLKf5dMCw
youtu.be/ALhMWR-3JJc
youtu.be/CEY3p29TOqA
youtu.be/oiyKRS8wHeg
youtu.be/zz4ZzNik1Y4
youtu.be/ZlgbSg6yOvA
youtu.be/Urj70kPy764
youtu.be/_P8F_AgOnnk
youtu.be/ito9f_siArI
youtu.be/i_6nwvC_8D8
youtu.be/HjXBxW52y0g
youtu.be/zW6iL6Dez-c
youtu.be/EHleKfculic
youtu.be/mra75m2BB6c
youtu.be/ybd2N44xA8M
youtu.be/aRYq14jsF04
youtu.be/9c5r_xS5HdE
youtu.be/gQ6M7AbMudQ
youtu.be/ttpV7b-3bA0
youtu.be/4msXJpqw8Rw
youtu.be/ne74nsRQVTg
youtu.be/PMuzpn5fUNg
youtu.be/SCFLgXxqDE0
youtu.be/v10LXVzrG74
youtu.be/oFqY0Z0yXxo
youtu.be/0yy6kKSExus
youtu.be/HJ0EE4LcvKw
youtu.be/PErilXwsIhg
youtu.be/zWb6NgzKSN4
youtu.be/kK4TYXzP9Ek
youtu.be/Q_rL0r5yPek
youtu.be/HHHnBm5wDCE
youtu.be/l3-uS8JO8yc
youtu.be/Fowj1ZF0JgQ
youtu.be/C21Vgx--QiA
youtu.be/wRHCh3NAj_A
youtu.be/KhiNrL5s9Qc
youtu.be/htRavAZ6jVE
youtu.be/ySfsyLfgKbk
youtu.be/nv7jdhdOPYI
youtu.be/wofveSldnSM
youtu.be/yxOtUJ5amaw
youtu.be/eDcH6NLs1a4
youtu.be/mktijzRxniY
youtu.be/E3InZNEWEjA
youtu.be/PIPbKNyE6tU
youtu.be/uDnd_C8Hkp8
youtu.be/-x2rbkEjjsU
youtu.be/T9WkRYMfvp8
youtu.be/m7h7TmbH3HI
youtu.be/3rJLKhsyZ8Y
youtu.be/z6gA49-gqlg
youtu.be/gUl1zcusSdo
youtu.be/S1E6LcUk1Yw
youtu.be/8Aj7-Aqy9nI
youtu.be/NYkW2vxyioc
youtu.be/OsdUtaktMsw
youtu.be/drraGGQk5fM
youtu.be/JgZLKBHPbhQ
youtu.be/PS2cP2SGKtg
youtu.be/WUe45KxAL9M
youtu.be/5tFXL4SM22c
youtu.be/Pm_PxmQIInA
youtu.be/i-6JZ862OqA
youtu.be/15uZ3VWZgtI
youtu.be/8aYlOlfyeZ0
youtu.be/dX21lZFSF3E
youtu.be/qJ9HGZEWIJs
youtu.be/YCm_PcBuTW8
youtu.be/nU2ETmokHvE
youtu.be/TrEq88wu2uE
youtu.be/lmzxETueTcw
youtu.be/2Y6YSSaZhqQ
youtu.be/ZUJ4VuR1iEc
youtu.be/T-zh_PJJY2U
youtu.be/kXkOH9vYIt0
youtu.be/OrP9l7KVHP8
youtu.be/wDCeS-e3QKM
youtu.be/EfvNgwLs56g
youtu.be/1PSz1X-zXEE
youtu.be/JHE3OerDKEY
youtu.be/9k9NMbQe0C4
youtu.be/m995J9uom1Q
youtu.be/YKZ3PV5mBGw
youtu.be/PhNOp0A7Mo8
youtu.be/t2UdqH6h5oY
youtu.be/IaNHt5kX864
youtu.be/ohDJF8DIrwU
youtu.be/u9OQMBPrFgI
youtu.be/SFVyDI9odTo
youtu.be/WAaPhJr1npg
youtu.be/3030tfM4VPM
youtu.be/Ev8tU9YItT0
youtu.be/rKDl37lqEBg
youtu.be/j3_8_F8NYqk
youtu.be/cwStXE3oDRU
youtu.be/Hj5CvP-5PtE
youtu.be/upTpOydT3Nk
youtu.be/H3PulV5mBek
youtu.be/TvyReEsQGXY
youtu.be/FVEDmcUrq6g
youtu.be/P3Bn6WHKaCM
youtu.be/aopetXCSDTk
youtu.be/KbPTkzNf7YY
youtu.be/QHWQo0Iv99E
youtu.be/Z1th19ANVQw
youtu.be/kDQ0fZ7RWjc
youtu.be/unt4QbDFNF4
youtu.be/HoJofdXHTek
youtu.be/GErM3s20OeM
youtu.be/9cBgKSuzoec
youtu.be/lpUDsSSExpA
youtu.be/P7fHYSyvxU0
youtu.be/buNYP7F1eHc
youtu.be/rbowIy6kONY
youtu.be/2zz6BrCmwRM
youtu.be/AaQu9Zia3gY
youtu.be/xPUiHrflJos
youtu.be/eC1T6gtzbjA
youtu.be/QadQTnxLfF8
youtu.be/cMtIIcN0lZU
youtu.be/a1i-x0qbHFU
youtu.be/ZVEWyrtqm4s
youtu.be/ECWs50Kmdr0
youtu.be/7D9XZdDoVAM
youtu.be/GWPC3HpaJ-E
youtu.be/rnW85WwPlu4
youtu.be/kujxzzui0nI
youtu.be/zm19QrSDJ1w
youtu.be/06wWpmOkVCg
youtu.be/pfAFYQk-Ek0
youtu.be/uaLdOFqA2zo
youtu.be/nbU813jylm0
youtu.be/gKviXbX8xGM
youtu.be/Y6KfK7r60PY
youtu.be/OKVi7aClKrA
youtu.be/mTo8Sh2QRgE
youtu.be/v8pijjIsU-E
youtu.be/KsPbgpcQ-S0
youtu.be/6RPRzN4kTWI
youtu.be/287LWsmCrGQ
youtu.be/tG3IGJwDBxM
youtu.be/st5oDePYr3s
youtu.be/04q6xmXbQLo
youtu.be/1oLBAMzbS74
youtu.be/BOtzVntvtiE
youtu.be/AP3StF0nl0M
youtu.be/ptiuTxvk_NI
youtu.be/betbw6lR9vQ
youtu.be/0Tg8jbY0Kv0
youtu.be/BOO29iNw61A
youtu.be/NrolxaxNj50
youtu.be/N_RRyFNUtSg
youtu.be/TSSMtIkVOxY
youtu.be/6HeF99VRTiw
youtu.be/lpVnTMsMMws
youtu.be/h79U1tAAzvo
youtu.be/nq7SqRe26vY
youtu.be/BY5ZZG4nBUY
youtu.be/5n24yLFVq3E
youtu.be/-Js9nZhGC0c
youtu.be/1jdJrxItqCU
youtu.be/7Icz_qVgJYE
youtu.be/KjwHKMjr_1o
youtu.be/6aq74_B7fFY
youtu.be/W3i4qcBD7PE
youtu.be/lVq8o5ETBCM
youtu.be/30crnm58XjA
youtu.be/g05fUJe-EfI
youtu.be/AlUNBHMDoIw
youtu.be/8MqU869oKSk
youtu.be/SfS03lYAZIQ
youtu.be/Glq7era7BqM
youtu.be/Zb7ULyZwPfc
youtu.be/wCNNDojIDto
youtu.be/MPvy6pl2oAo
youtu.be/VTaHgEqtygY
youtu.be/odyKx-FJdIs
youtu.be/olnuUAHx3Xk
youtu.be/nbPSIh1SU8w
youtu.be/spGJH6zUfuM
youtu.be/LjzzbEmsk4E
youtu.be/saOXLxN8PRg
youtu.be/JguhnvJq3yc
youtu.be/rynWDSAkMok
youtu.be/XAq-Y_R_0Ic
youtu.be/KS9UbjSNoFA
youtu.be/os_ORVQjItg
youtu.be/ib3j6BuAi_M
youtu.be/RKCwMxDenTY
youtu.be/oA-0ykCP95U
youtu.be/hTme-ZMV7j0
youtu.be/sEhV7FNpYNE
youtu.be/GBGShUmEAFA
youtu.be/JJxmx63vMFU
youtu.be/9_uzE0-XR0E
youtu.be/zHTOsIBiZhU
youtu.be/BE9xnDYBGtU
youtu.be/xTSt3TetjxA
youtu.be/pu0uAQ0BR5w
youtu.be/pi4nXB-gy7o
youtu.be/350bk9Ph3ak
youtu.be/rEexWr_-Lm0
youtu.be/mvpsW-S5128
youtu.be/SUt70raWU2E
youtu.be/rGoqF0b_A48
youtu.be/DyiH2xcebpU
youtu.be/4y6_nqMbdiE
youtu.be/_kBtqVc5DwU
youtu.be/-xPAJzetG7Q
youtu.be/qh-KzQz1rgo
youtu.be/HQ2lv7MuQRM
youtu.be/8Zjra-V5kjA
youtu.be/GR8bmbiZFtY
youtu.be/c9vSFIZIUsc
youtu.be/iiN1KFyUf64
youtu.be/tnvzQyKLcw0
youtu.be/dHJ0KMpp9jI
youtu.be/j9rqfyuJ3gk
youtu.be/e7PbGT951bk
youtu.be/08eVwHB6OyE
youtu.be/haaZ-HmVlJE
youtu.be/C7Ngj36q7Lo
youtu.be/ynMj6K5mXO4
youtu.be/L1cVLunJiDQ
youtu.be/Ah0tVPfMbPQ
youtu.be/tomjDWvnW7s
youtu.be/k8NSru-dB5o
youtu.be/gzDf0VOhq64
youtu.be/60sAaXOONAE
youtu.be/SiN_kah6sN8
youtu.be/VrbkXBnueJQ
youtu.be/LzOHL-WTCUA
youtu.be/74jIxFQx95w
youtu.be/-bYEhd1a1Vg
youtu.be/fumqgMhVH9o
youtu.be/heVCe2eTi-s
youtu.be/9P7LkwIRkP8
youtu.be/5QfzcjIdcJ0
youtu.be/Sakma10-kjw
youtu.be/ieyFElnTpuA
youtu.be/TiXSP5qZIFI
youtu.be/ZGDdR7McG-E
youtu.be/OD-sDlSDrKk
youtu.be/7NyUmQfhgNg
youtu.be/0MhG2WoJz4k
youtu.be/dm_ob5u9FdM
youtu.be/ZOYaG182SmI
youtu.be/K6mS8znoAzw
youtu.be/Ej-maa6sX3M
youtu.be/ZWrMhU577SY
youtu.be/nq9H3AdQ7_s
youtu.be/X662diihNUQ
youtu.be/iSwT2NekAI0
youtu.be/nRx05b_j3wk
youtu.be/oQ09Y-ffKWI
youtu.be/7m_lG5uwupI
youtu.be/b2taSMx6394
youtu.be/nzeKHP-lGyo
youtu.be/qeMcDe5BtFU
youtu.be/RXOzqEO_R0Y
youtu.be/6PwEAQPcuVo
youtu.be/8boxip4om7w
youtu.be/W2pkzky01Fo
youtu.be/9wt-2SQNSsQ
youtu.be/h_xBEhgBzvA
youtu.be/xrPZBTNjX_o
youtu.be/S5LtFjrI_Gc
youtu.be/C4u5XkZHL2U
youtu.be/RRJ4njY6rPQ
youtu.be/lGToxTDq2eQ
youtu.be/LcmPyHWO4Pk
youtu.be/KrbyVUHQasc
youtu.be/DD4F5it7a5M
youtu.be/1zTynaDQ1kc
youtu.be/iLUR_k52lmw
youtu.be/awM4RlbSsIQ
youtu.be/SbW6FTU69bw
youtu.be/4xkRcfeGDoo
youtu.be/HcaU_O0qU5k
youtu.be/KEGXB5Xt3vU
youtu.be/L1K_fIA4HP8
youtu.be/arxlSmPhpro
youtu.be/OhisEReiEIc
youtu.be/dcmiRhS464I
youtu.be/BLZUNeADz9c
youtu.be/IGovSgF_h4A
youtu.be/jeOaY9m8JRw
youtu.be/BjXTNP73yJk
youtu.be/R0saAFqmzXI
youtu.be/QnVlCvqAYZE
youtu.be/gHny5-c_Heo
youtu.be/Ue-Ce2Yn-mQ
youtu.be/EEpfcA2FSdE
youtu.be/FhJbXPvSDKE
youtu.be/1LA_LtrnhsI
youtu.be/ONisoHrkPw8
youtu.be/RKGM53g4nBQ
youtu.be/RHTHaRIhL58
youtu.be/YEeGESWix8E
youtu.be/wicouWTKxjY
youtu.be/0wXWEdipBEg
youtu.be/uOxppT3gPpE
youtu.be/12KHyHYOJbo
youtu.be/oQSLls9COUw
youtu.be/x5wOX4NSb90
youtu.be/LKLbPx5zg94
youtu.be/xt6w0uVjZW8
youtu.be/ZUEkNRuzHFA
youtu.be/vmhOj65aaY8
youtu.be/xWdAZEezdQY
youtu.be/R9EfYNSvU-4
youtu.be/CsXYUwlRMXM
youtu.be/AQz5u71G3js
youtu.be/2qy9PWaGpI0
youtu.be/ugm3DO6vfCw
youtu.be/R-ZTc5bdx8Y
youtu.be/lpxRE-jZMks
youtu.be/31tnXPlhA7w
youtu.be/4Tx3B0Jzfh8
youtu.be/fihPm0Tr8a8
youtu.be/BpHSm0KcW7o
youtu.be/Yl8dQdHwgAQ
youtu.be/wKI1IZ8F8mo
youtu.be/G2u-nB1zxMA
youtu.be/JsImx15Humg
youtu.be/gaC1Kmp_ZMc
youtu.be/ixIfKFy7QTg
youtu.be/NRC8kVJdtM8
youtu.be/YqNMvcEIAQA
youtu.be/ZTdif8x_Zak
youtu.be/PXqudmtJ-_E
youtu.be/aHyus_bETtk
youtu.be/KrrgcOn2A2A
youtu.be/vDbI57A7gLo
youtu.be/14pXHe7qmns
youtu.be/Pou3sGedeK4
youtu.be/smmxXTUc3Js
youtu.be/aiVNvQyDuXg
youtu.be/p4jpChlgi0M
youtu.be/w8LfHDcHsmI
youtu.be/z_cIF3BGctM
youtu.be/gUigD3UBNBc
youtu.be/DiG3sgmGS3s
youtu.be/FWTLN97bdzM
youtu.be/8H7ZGIDmuIw
youtu.be/5fPlLX9_WI0
youtu.be/047C-mMQpSE
youtu.be/hAiDM2nz7aw
youtu.be/_QZgt-nA6nY
youtu.be/YNVcvXYJ7_M
youtu.be/zMCl6X3nPpQ
youtu.be/UxTSj-SS6K4

In [ ]:
df_crime = df_all[df_all["macrotopic_pred"] == "Crime, Security and Justice"]

In [6]:
df_crime

,video_id,text,channel_title,published_at,view_count,like_count,comment_count,occurrences,toxicity,severe_toxicity,...,perspective_insult,perspective_severe_toxicity,perspective_obscene,perspective_toxicity,perspective_identity_attack,perspective_threat,macrotopic_pred,macrotopic_prob,lifetime,send_count
163,RJHPxSSV-QY,realize arrest agent exclusive deal enter prom...,Dr Insanity,2023-08-18T01:23:38Z,7296140.0,99535.0,9600.0,"[{'id': 535094, 'folder': 'channel_1819679478'...",0.002060,0.000096,...,0.042665,0.005684,0.101091,0.188392,0.005846,0.049451,"Crime, Security and Justice",0.652230,1.0,1
338,l67lO2nSAzE,seek touch child near park chicago police sexu...,CBS Chicago,2024-09-14T15:02:02Z,847.0,13.0,2.0,"[{'id': 16197, 'folder': 'channel_1474635205',...",0.039143,0.000210,...,0.068515,0.377512,0.056583,0.153432,0.136166,0.023077,"Crime, Security and Justice",0.952038,1.0,2
370,5x4siLUmlzU,bodycam footage deputy shoot outside macy sant...,PoliceActivity,2023-04-14T22:29:57Z,823291.0,21782.0,15420.0,"[{'id': 238528, 'folder': 'channel_1293013534'...",0.006231,0.000134,...,0.000417,0.219100,0.035847,0.066696,0.283622,0.014253,"Crime, Security and Justice",0.834670,1.0,1
423,D-bL1bB0PA8,trump narrowly attempt miracle luck speech tru...,EXPAT American,2024-07-29T13:55:00Z,1845.0,65.0,7.0,"[{'id': 2904, 'folder': 'channel_1661480713', ...",0.001051,0.000101,...,0.027255,0.088748,0.031980,0.025542,0.009619,0.003529,"Crime, Security and Justice",0.327815,1.0,1
502,1ugs4LXI02o,body camera footage sonya massey shoot stateme...,Donut's Raw Police Footage,2024-07-23T15:27:55Z,101331.0,3604.0,2625.0,"[{'id': 10567, 'folder': 'channel_1884199968',...",0.001088,0.000112,...,0.033460,0.007210,0.015154,0.060120,0.001513,0.112023,"Crime, Security and Justice",0.780662,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673285,_Bqu--JgUxA,protection anthony fauci title lock title lock...,Ben Dykes,2024-11-17T01:20:47Z,29389.0,4816.0,321.0,"[{'id': 96599, 'folder': 'channel_1409530069',...",0.001657,0.000095,...,0.014506,0.008156,0.060653,0.001993,0.004773,0.024253,"Crime, Security and Justice",0.816490,1.0,1
673305,bBVt2gvKxRI,postal patron uncomfortable accost cameraman o...,Liizrdmedia,2024-05-29T16:02:55Z,14795.0,630.0,285.0,"[{'id': 22434, 'folder': 'channel_2138283473',...",0.000775,0.000113,...,0.011832,0.006770,0.040678,0.001101,0.002886,0.021997,"Crime, Security and Justice",0.678248,1.0,2
673309,x_JC5ugiqt8,dallas mega pastor arrest shocking reason dall...,Dee Wats,2024-10-27T19:30:05Z,23051.0,557.0,96.0,"[{'id': 17438, 'folder': 'channel_1654067847',...",0.002244,0.000095,...,0.042589,0.016638,0.158220,0.004597,0.068466,0.063025,"Crime, Security and Justice",0.623561,1.0,1
673402,sxy22Eq5JfY,iowa teacher fire student turn strip pornograp...,True Crime News,2019-10-21T21:01:55Z,5162848.0,55386.0,27368.0,"[{'id': 1056, 'folder': 'channel_1654235374', ...",0.509905,0.001518,...,0.075614,0.024581,0.360437,0.020774,0.042293,0.159116,"Crime, Security and Justice",0.820751,1.0,1
673586,fNTfEPLoAik,clark county sheriff arrest felony count clark...,WLKY News Louisville,2023-11-09T09:24:16Z,358.0,5.0,NaN,"[{'id': 86067, 'folder': 'channel_1172210773',...",0.007710,0.000096,...,0.023867,0.094817,0.003281,0.009175,0.157584,0.024235,"Crime, Security and Justice",0.869761,1.0,2

In [7]:
for index, row in df_crime.iterrows():
    print("youtu.be/"+row["video_id"])

youtu.be/RJHPxSSV-QY
youtu.be/l67lO2nSAzE
youtu.be/5x4siLUmlzU
youtu.be/D-bL1bB0PA8
youtu.be/1ugs4LXI02o
youtu.be/VVUrP9b9u3I
youtu.be/iyxCivipvKw
youtu.be/lHNobRT3czY
youtu.be/3NxLb7i0eYA
youtu.be/iECyoVltdlk
youtu.be/8Gmq5BEVgxg
youtu.be/L-JQeqTXYu8
youtu.be/_IQXXRGlnzI
youtu.be/oGyAMkanF00
youtu.be/9KjzwTRXKaQ
youtu.be/eq3brUMm3gA
youtu.be/UIL8xih3F7w
youtu.be/uwWOMwIS1T8
youtu.be/o4EDHDJEGZs
youtu.be/2tGTCDfUAgY
youtu.be/gtjsmY73wdE
youtu.be/yQQQUL3vLIw
youtu.be/D-OeJAwdxpY
youtu.be/Ux3tYbR6bFI
youtu.be/2SD2bGzrVyU
youtu.be/OLcr8a0e2dc
youtu.be/7zirKYk-sZ0
youtu.be/pH3eefjYU4s
youtu.be/iLGN1IEzopw
youtu.be/c3pyzErrj08
youtu.be/1MjojhUr3IA
youtu.be/1qi55yGGoig
youtu.be/4d3VAQRRCGQ
youtu.be/6NcxPh5Jb7M
youtu.be/XIBKRT_XsX4
youtu.be/LoQQyaHmvbI
youtu.be/-XFBVAAzXjc
youtu.be/dMo4aR8B-0k
youtu.be/B_V2JyNTrvk
youtu.be/FiT2yqGWxOo
youtu.be/1qOfAVzR7Js
youtu.be/HGcN-kj5W3I
youtu.be/ZogPG3v3BgY
youtu.be/oUP3mh8wzvs
youtu.be/Na2hOcx4uX8
youtu.be/Kp0ymAmV6oo
youtu.be/fhu006vV0zQ
youtu.be/VWDNlTjVqcA
youtu.be/ZIMVOXkucB0
youtu.be/7jdRv43ND_4
youtu.be/1_yWwVPS3AY
youtu.be/hT8nxsVAc54
youtu.be/1QZwbjTFcXg
youtu.be/tWyxKarVc5E
youtu.be/n-5fYMh7YXw
youtu.be/b8V7OneFLnc
youtu.be/2eHqL0qF2DI
youtu.be/xoldyDQNBXg
youtu.be/2IY_Fg4OsL0
youtu.be/eHZTkui74fM
youtu.be/DrY1sauUtis
youtu.be/8CZlXFAMrvc
youtu.be/5-wqNEGeBac
youtu.be/4PRv1KRCgaA
youtu.be/nlTnomJz5DA
youtu.be/3P6QYqxdXm0
youtu.be/AO1czwueFJQ
youtu.be/H8sTdGdSQ2k
youtu.be/XJ7i8huOQoY
youtu.be/hhxXcRLkHww
youtu.be/VELLZYwOqtI
youtu.be/dNAg-7nSJOc
youtu.be/SckoSdZubxY
youtu.be/FjlHTl91X_M
youtu.be/yW2_Gr0gHGc
youtu.be/UB_Gs-0dhOo
youtu.be/ehOs-B_A2h0
youtu.be/uz-fsNADqXI
youtu.be/FeHov4HLo8M
youtu.be/RFKYKJDGwfE
youtu.be/NIwJiIJNRYM
youtu.be/86DZNUYRIbs
youtu.be/JBqG5gtI514
youtu.be/7iXt689H-Tk
youtu.be/AKoLj7MoVpo
youtu.be/jUlVOx1DqCg
youtu.be/PUqivBwuZIA
youtu.be/QS-Mhja3XYg
youtu.be/-aHU5mJrnyI
youtu.be/uPoutmvgzmU
youtu.be/gTLAGOTcxo0
youtu.be/yt4rmH7EwP4
youtu.be/xutUpV8cBt8
youtu.be/GHnK0o9d7TE
youtu.be/GmBtL_zbRsc
youtu.be/lcLS9qDgCuc
youtu.be/i8D6UORNcfI
youtu.be/CDQYRnAwpxk
youtu.be/TouT1TGUbQE
youtu.be/YEx-6W_tZ4g
youtu.be/WPxZPgliZFw
youtu.be/MbgW9C9G0H4
youtu.be/ZBd0v9Wugco
youtu.be/dHL8cxpPj1w
youtu.be/9_P0h16N0_Q
youtu.be/oT7faCe5zJ8
youtu.be/uzaYihTFGAk
youtu.be/xw-HJK55YUI
youtu.be/E-c8rAT3fIg
youtu.be/02VTV8PK-Dw
youtu.be/wK7a3UoIpXY
youtu.be/iwv8CtpRrWU
youtu.be/mVpr_ciMGpQ
youtu.be/y-CB0qxGvC0
youtu.be/RPmkRjCEmjE
youtu.be/OzGtphDtFvY
youtu.be/ZKugbv6jp9o
youtu.be/dRQeUcYZmrY
youtu.be/1WJinrgjU0o
youtu.be/0S0Nvcj3nDk
youtu.be/4sYz5zE8lac
youtu.be/KdpWDELFSDM
youtu.be/wgyEUfHT3lw
youtu.be/JtqrE9985Ss
youtu.be/ArPFc2m6Iy8
youtu.be/4AfEKbihnd8
youtu.be/JEz8IXWOdi8
youtu.be/EtqCgkOOjYc
youtu.be/JbW2g5W8XJ8
youtu.be/WFdYk0ZAi0Y
youtu.be/RRfCwrI--is
youtu.be/9fAojfpMlfo
youtu.be/52UesHksX-k
youtu.be/FpgJ5w-Idh4
youtu.be/ok22fqgN02c
youtu.be/kuSmgqzcc7M
youtu.be/jtRU3vZI-QU
youtu.be/UaukbRmjrRs
youtu.be/rPqy04mKAso
youtu.be/2KdAY_jppPk
youtu.be/8pQBHuA-oXY
youtu.be/nQgYbsrmH7s
youtu.be/hzZcwIhW5Hs
youtu.be/INdHo3NcBQM
youtu.be/YJ_2lUwVA5E
youtu.be/iIlauy6Kwl4
youtu.be/ffpN2QAdS0k
youtu.be/WmdwhEObxc4
youtu.be/bCmoAhMKaco
youtu.be/vLY15ClxMNI
youtu.be/GeHpRKxIfbo
youtu.be/QI11yrWWMu0
youtu.be/4onEBnM5mS8
youtu.be/E3QGJmcT3L0
youtu.be/YeqNKTEJyqY
youtu.be/Kr6-tLbpHEA
youtu.be/_GR7UiLw9Ww
youtu.be/jf4ZrJr8HGY
youtu.be/-ljAGtpg4sI
youtu.be/Oth-yG44_Wc
youtu.be/NSBxuGBC0vc
youtu.be/Yvi7nYRFzF0
youtu.be/6jgvkzD8d3k
youtu.be/IFcvs5YzRqo
youtu.be/s7xLGsYdg70
youtu.be/-xL4ZOU8rz8
youtu.be/aCfrpis48os
youtu.be/MrrrEJowmXs
youtu.be/DqiburgGzN0
youtu.be/yEui-ZbHZfM
youtu.be/JggxgaRiVTg
youtu.be/vHrM3ocOEvA
youtu.be/Iw9KSCZAUyo
youtu.be/cD634S3JxQk
youtu.be/4ysP9ORbDss
youtu.be/8iTWBHkn6eY
youtu.be/79VdFldr-c0
youtu.be/g6YEfft2TGc
youtu.be/Jc59wLzkHbg
youtu.be/0ovmbQivjaU
youtu.be/105mqMw58JU
youtu.be/ULjnILBGRaU
youtu.be/Cb9yEnSskO4
youtu.be/p6tBMHB-Lcw
youtu.be/jPirnYTkNRc
youtu.be/3nMWimwNLS0
youtu.be/Dx0I-x5lbgM
youtu.be/8eZ9ByBiYZs
youtu.be/PYbRqPrPzHs
youtu.be/hyNprlSNhQ8
youtu.be/Stft_t48Hxc
youtu.be/J4K1EBVK8sc
youtu.be/ENLi9baPFZM
youtu.be/jQYP05h2Vcs
youtu.be/FCuy163srRc
youtu.be/lyCBPKiSOIQ
youtu.be/Akwt6BoEsXY
youtu.be/QAXW_9FgusQ
youtu.be/MtQOzE4yzew
youtu.be/XOpCTEmJ3Ig
youtu.be/zaoIMq8GEsA
youtu.be/rc-nFabyHq4
youtu.be/ULEr4l9mzfs
youtu.be/qO3BkynqX8g
youtu.be/ZYHZzVayPpg
youtu.be/IHeQ364II1o
youtu.be/rsBViJborWE
youtu.be/USIozcCSM4g
youtu.be/gDiQEMW4ER8
youtu.be/LLezY3KzGJY
youtu.be/Cb3-tlyuhVo
youtu.be/HpSMpat4GZQ
youtu.be/blTjzcdAE3c
youtu.be/lbyawBDThLA
youtu.be/bfcAwc0UTVY
youtu.be/uLQvBmJ2yoc
youtu.be/nVRN6ziyTxc
youtu.be/j3YUIWcNtGs
youtu.be/UvXlZwwVWGk
youtu.be/vbY-g9hnL14
youtu.be/701rN3-makc
youtu.be/peD8g3A5u00
youtu.be/EssDs0LKOcg
youtu.be/VleX0jofZss
youtu.be/_lj1p7_PaYA
youtu.be/BNOp1RfzVU0
youtu.be/06KcGtEVxTo
youtu.be/TJcx75R7_JE
youtu.be/XKnWByMs4DQ
youtu.be/I_uZs_F0YGw
youtu.be/H9jVEXdEfWg
youtu.be/P68sp1X9upI
youtu.be/vmeusvXptSw
youtu.be/LFMAmXZ7rl8
youtu.be/-kvMF-ggJAI
youtu.be/YpNAbdLGFXQ
youtu.be/gIAbmp3cX0U
youtu.be/GJV9kWdOiW8
youtu.be/UEblfe-aMJQ
youtu.be/oruLIfmf2AQ
youtu.be/1YYVywapjKI
youtu.be/EXmmBrVyE-g
youtu.be/-sntzHtOX5A
youtu.be/c40ryxaWaWE
youtu.be/EwA-2_6D8TI
youtu.be/jDcV6KqzE_k
youtu.be/zKbhSFpT4aA
youtu.be/YHs9OLgt8vI
youtu.be/5Li5znDxZ0I
youtu.be/rjdt7n6FZZA
youtu.be/lfBCca_Yedk
youtu.be/1FmP36FLfSU
youtu.be/I3PQLpikDqI
youtu.be/d0hsA0DmS90
youtu.be/qJkeY6lTsHs
youtu.be/EgFYjqMEy50
youtu.be/UqDku_cYSSw
youtu.be/VF7nRlv9Lbo
youtu.be/zY17_nraW68
youtu.be/ccFF2iEglQ4
youtu.be/-HA8kSdsf_M
youtu.be/TdymKHjA-J0
youtu.be/6ab8-TQD3mw
youtu.be/-RyjQGCSlz8
youtu.be/jQ5X53W5YGA
youtu.be/8EUKpjl8wVI
youtu.be/jsJhrSR_CgU
youtu.be/P0Ylop5Ae5M
youtu.be/OTSVIv_9YU0
youtu.be/RUd9Kh61Cn0
youtu.be/pZjDdNBzDho
youtu.be/pstX4c3QwQ4
youtu.be/ClR9tcpKZec
youtu.be/l5T2yknSQns
youtu.be/BDIw1l3r4tg
youtu.be/nfefxe9GdJw
youtu.be/tFOYgBGWgpg
youtu.be/nJbLMFpFuh0
youtu.be/uXN0ffMGGGE
youtu.be/BeDCTthCBCQ
youtu.be/9Ninmnm-vN4
youtu.be/lAoFE0d_354
youtu.be/23zqbJ_5kXw
youtu.be/nNB1-IYh23Y
youtu.be/K5wch3j-vbQ
youtu.be/f9UCtMcf4wI
youtu.be/qKJ7h-eLn_8
youtu.be/nC9wb_CTTLg
youtu.be/3eFg3zUrW1E
youtu.be/B9C3SAdw-AA
youtu.be/ioZiL_BQdwA
youtu.be/enspKbIW0NA
youtu.be/v10FMvkFHVY
youtu.be/edw92sH1gkk
youtu.be/HxCpRb0E2C4
youtu.be/4_JwzjhwAW4
youtu.be/KMTEh-nNyBY
youtu.be/e17Vnh51aYU
youtu.be/FzL-7FK4Ky0
youtu.be/xJQIYk0nsvI
youtu.be/72Z8AUiASBo
youtu.be/VTjRMD6Z06Y
youtu.be/GDISW0J4_xc
youtu.be/JyQn7TeRRvs
youtu.be/68d579_EtDQ
youtu.be/waXHhw-I9aw
youtu.be/Wgs3MT7-YJQ
youtu.be/6Vo7ppZ6aQ8
youtu.be/-eUyng4f7KQ
youtu.be/ezZ_DcmoANI
youtu.be/LR7jdeUgRqs
youtu.be/dv0d3MerOBo
youtu.be/W5-5GKNlcIs
youtu.be/DMxTUHyEhf8
youtu.be/pAUZn1itiiw
youtu.be/TuvrU-CUEYo
youtu.be/1BxB9Lnx_4c
youtu.be/6_l8l5Y2PSM
youtu.be/N-Umf_chNHw
youtu.be/z8X4DB-ecWM
youtu.be/8ywO6dloQ-o
youtu.be/YQjPWZuqDOU
youtu.be/1vdn3CnZ9kg
youtu.be/mUT40UhxrUg
youtu.be/sNC1RKn1wE0
youtu.be/Wfg7IJK8Jfg
youtu.be/I-9rCMBMh-8
youtu.be/D00hAP-HuKk
youtu.be/z75YyF3WYCw
youtu.be/7C06w4LoP_k
youtu.be/qRNDgFvoRjs
youtu.be/RUvIQJo2j5g
youtu.be/hS2131Z5V3U
youtu.be/Mu_KjHDGBiU
youtu.be/4sPj8HhbwHs
youtu.be/yTXFDTP-i90
youtu.be/9yNkcpRRdqA
youtu.be/-jLIBeaLwW4
youtu.be/RjYuJeIaF4g
youtu.be/ArH0mhK0tEY
youtu.be/MXwoz7XKzt4
youtu.be/ClA1BuzB-_0
youtu.be/la5m9c-_waE
youtu.be/u08nnck_zSY
youtu.be/rorvKWop_hc
youtu.be/P3OikMrqiAI
youtu.be/wlTJ5sf_UJ0
youtu.be/Qmmm6-Uvj70
youtu.be/_kPIeeBCY2I
youtu.be/fDKBJ4yqSuQ
youtu.be/scUAU0YeCbk
youtu.be/Rz0HNlsSpgE
youtu.be/YqrdC1kBaxM
youtu.be/kp-KMTW2YKU
youtu.be/G-yB6fUVXZI
youtu.be/0HaEUyiUwJU
youtu.be/L4-I8RNyUEA
youtu.be/AwpRgNyljz0
youtu.be/30WujIWVKqk
youtu.be/f1agQE9Hr08
youtu.be/Qyj8P4av2qk
youtu.be/7HiXkhzvDuE
youtu.be/evvBpjFf_t4
youtu.be/l1hYlvjz67A
youtu.be/E6L4sP7Gras
youtu.be/k1b1M9lPJ_k
youtu.be/XAW3SoGevgg
youtu.be/nv-wBuK4bNU
youtu.be/X3j8-RF75P4
youtu.be/s66Xgr3SYbQ
youtu.be/nZbbbYHgRjI
youtu.be/Mt5nImerPZA
youtu.be/6mpp5BljAR4
youtu.be/dkuINe_mIHQ
youtu.be/c9qVdI7rh70
youtu.be/N3QG3135Jqc
youtu.be/4TsAUz76gNs
youtu.be/Jcz9Eune7BY
youtu.be/iEgvZSy_3fM
youtu.be/YJ4c5atUjsE
youtu.be/L9Rgq6jo3lE
youtu.be/YwSD6yv_eIU
youtu.be/kxSi9BL9hkw
youtu.be/NEQtUmvH97Y
youtu.be/T5J8ik0Q66c
youtu.be/y5f-EYzS25c
youtu.be/qJqDguQX9rc
youtu.be/o2etXCT3FUo
youtu.be/SdFY2AKJIGw
youtu.be/nmYmTN_4yb4
youtu.be/b6cfweSPFkg
youtu.be/0hk-5LovF9I
youtu.be/wWAuNoLQXOQ
youtu.be/kwOVtOHi8qI
youtu.be/KSqID01IU-8
youtu.be/BunKdvqKVoI
youtu.be/lyqgFqcGAHY
youtu.be/S9Z5Sq_SZaI
youtu.be/UiRySXzyqk8
youtu.be/awizd9G6Bpw
youtu.be/F1Q9A-ylrS0
youtu.be/fQP_VNMLrHw
youtu.be/OKpAHP0GJlw
youtu.be/foj4sfQP3ek
youtu.be/b5Z3VNTjXIc
youtu.be/FWBcYRoL770
youtu.be/e6qZmZKn2xE
youtu.be/b7mHd5JOjP4
youtu.be/SVzitycUX6c
youtu.be/NEzKcdIICJs
youtu.be/VLXCJcO0_wA
youtu.be/qQ2CbLzOtmw
youtu.be/Yymc2EgGrVc
youtu.be/F9keG_jjiPE
youtu.be/e42KqA9JsZM
youtu.be/5SWqQ1tNQag
youtu.be/htzmk9nqk6o
youtu.be/wsd3_MxpRns
youtu.be/CvQJnDjZzh4
youtu.be/oaG8gBP4nT0
youtu.be/kDYyFzTQRfE
youtu.be/y_RY_cMQrZ4
youtu.be/oPCJrNy2bq8
youtu.be/09RTtPV9ToY
youtu.be/SQBLDFiUKag
youtu.be/M7yGiZpYD2w
youtu.be/VnSAVLy9WlM
youtu.be/C_dTKA7EdtE
youtu.be/G1p6rlDCxq0
youtu.be/mW86JFn8lwE
youtu.be/c3aviwIfq2o
youtu.be/i44CohoU6e8
youtu.be/62i169x0NuM
youtu.be/wTHgMxQEoPI
youtu.be/09UdIqT0s9A
youtu.be/LrPxoInRR4I
youtu.be/o07CIrbrhMM
youtu.be/KqNqOjRlkgs
youtu.be/aSc8XurQ4_k
youtu.be/4iN1z_vwGgE
youtu.be/TQVGKCEgXoc
youtu.be/CH_lOKssklk
youtu.be/E-_RvbQX7AA
youtu.be/gTot3YQ16fI
youtu.be/7MvHiyYi5w0
youtu.be/i0XGu6qMjW8
youtu.be/_tUctFu46_c
youtu.be/oFTPQvTYH0s
youtu.be/Vv9a_yeM89o
youtu.be/6cCfKho0pKU
youtu.be/IUpgEgTf1Bo
youtu.be/_wQovM_upMo
youtu.be/WUtxupyNCeE
youtu.be/5NR2N8wvjbA
youtu.be/57JfeDH4q1g
youtu.be/mH8EEou1MfM
youtu.be/-QHrZU43Dgk
youtu.be/lpsMzuOPguc
youtu.be/-xFrRbrRcQU
youtu.be/IALiNAzNKKw
youtu.be/2AdJCMgq3hc
youtu.be/fZ8Kkigpsb8
youtu.be/4puokTpKpcg
youtu.be/anofcdN-BsU
youtu.be/cidHiANNOVA
youtu.be/FLrv0rxZEJs
youtu.be/zwrqJa3RYsE
youtu.be/Kcz4Wp0-4o0
youtu.be/8zxPHcSSdE4
youtu.be/s5HZdhIGuB0
youtu.be/08WIBFQKwQ0
youtu.be/pKp6uD1JAdc
youtu.be/WMBgUO0IH94
youtu.be/u2i6ng6K7dM
youtu.be/uv-t8Ltkx6A
youtu.be/aDrhmqkYuoY
youtu.be/NINFxe9jBFk
youtu.be/Ru-99zY9gR8
youtu.be/HojQboWR3Z8
youtu.be/5zYTlnYIq1Y
youtu.be/XF6sjvkPM90
youtu.be/DjJ3l-GRm8Y
youtu.be/na00ri5z7X0
youtu.be/pywOEFToqzU
youtu.be/c9elH9lBzyQ
youtu.be/_4hjBDu8DsI
youtu.be/904X4iPOc1E
youtu.be/Sk6ZRne51gA
youtu.be/eF8-HjdOXhc
youtu.be/9J47CXCuqAg
youtu.be/bPjnU3725sU
youtu.be/mUMqaFMjc0g
youtu.be/TisxvqIWdXg
youtu.be/jeuSgtFepwE
youtu.be/1frIsIdDhpg
youtu.be/J9p_fVPr-TE
youtu.be/v1ZUfAsQw_E
youtu.be/Q_57kXiVKGk
youtu.be/xL38ARCbRwU
youtu.be/4rwCWXIlWCI
youtu.be/b598dL_mSvA
youtu.be/JpfEh6AFYAM
youtu.be/RUUj_qZ8Sl0
youtu.be/erEBP8Q6Cu0
youtu.be/b0WpZREc1s0
youtu.be/XgknM7fCmVk
youtu.be/Vmpvzuj5_GQ
youtu.be/w78_N_gWJQo
youtu.be/wmkomWEIGkY
youtu.be/mVSo62x0tg0
youtu.be/i74iNZWqFtU
youtu.be/gNvXE8WKeD8
youtu.be/i0bpNaoumLM
youtu.be/E_mpWWHIbgk
youtu.be/S2UvLfhdGb4
youtu.be/BIknR7ozoTA
youtu.be/O_eBAy8qCJY
youtu.be/MMttMeBxIvs
youtu.be/j8YnG4ndQk0
youtu.be/bsJM7khFtWE
youtu.be/dHoeS31zhyw
youtu.be/56bxF_nmXaI
youtu.be/-BkAoh9A5mg
youtu.be/4YoGVkjl_0o
youtu.be/zElEFA6Z4rE
youtu.be/Dh-XSRR55yI
youtu.be/19LQQjFUNzI
youtu.be/pvDDQOVJSj4
youtu.be/1NnKfc7hnkA
youtu.be/_k83WArW5XU
youtu.be/8Uf9uLvb0u8
youtu.be/M32DJblq86w
youtu.be/rf2qOUk48Rs
youtu.be/NdEAX7mezF8
youtu.be/dMpKASGaie0
youtu.be/HOQ2UdWdaNg
youtu.be/C4wb-4sxE84
youtu.be/d9GkNtxmk1g
youtu.be/O4cZTbs_1zI
youtu.be/ResDJCBNWzA
youtu.be/lRDcTiV66Bw
youtu.be/jTkmMBi8inc
youtu.be/O2d4mdC6v-s
youtu.be/DfwG-5OkTrg
youtu.be/dp7hrnf_ggo
youtu.be/wjjGue8TcIQ
youtu.be/BFygKTJEeCI
youtu.be/gSmB259mMIk
youtu.be/neV8nLBRam4
youtu.be/fMAxAp90b9o
youtu.be/zGtYELR3LdY
youtu.be/FEvV_jFoZHY
youtu.be/OHhiYdTGhVM
youtu.be/nnJW7hXeQvA
youtu.be/_h2vsvo8iig
youtu.be/__yC5oY1--4
youtu.be/EcuWUv4-m0U
youtu.be/7RORhH-o3T8
youtu.be/1syedjNro2c
youtu.be/tsF-g0nWVKE
youtu.be/H0X1lGWRPy0
youtu.be/xk3AzM-5RSE
youtu.be/MxvBzEXAqUc
youtu.be/l8PZprtWfNI
youtu.be/wDZiqf5bzwI
youtu.be/IS2LhK4L7MY
youtu.be/7EX738IPaYw
youtu.be/zLo7SukCNgE
youtu.be/6aWJW7-qaZU
youtu.be/jNCgjIhzG4g
youtu.be/nXSW7Mjl1og
youtu.be/7tCXMPKkAs4
youtu.be/sq2SdsfZ7cY
youtu.be/7jP3FGj7syI
youtu.be/I1cIkcXltPE
youtu.be/N-g-re65EQY
youtu.be/MVIPftcbw60
youtu.be/-ZvTQt-GVhk
youtu.be/SuZcxQzPeFw
youtu.be/8KTFY0djJoc
youtu.be/DUFhv7iKv-8
youtu.be/HfQ6XW4aoNM
youtu.be/2KnQ0kIHkbg
youtu.be/gpBhb176_Rs
youtu.be/XYxUD1dK-tY
youtu.be/7Qx7EO4BeO8
youtu.be/d4921LRDTQg
youtu.be/8MOLCiqjCNg
youtu.be/-zwq1w9BV2g
youtu.be/-UC8NQY4MdY
youtu.be/csmBA8QV458
youtu.be/anBof7abywM
youtu.be/P3MVcFt5WZU
youtu.be/sE5J4UxzxzE
youtu.be/GwEUyrtohuE
youtu.be/fRpp4iSgQH8
youtu.be/jqKjO7c7vq4
youtu.be/QG-TnMpwgCw
youtu.be/1TD682VMs0U
youtu.be/BDhR7rOX15c
youtu.be/4JxTAkwjRPg
youtu.be/10PCKWHMjwo
youtu.be/GTm4sp2haFI
youtu.be/iMoGQqwiek8
youtu.be/cbBLDMKU1mk
youtu.be/dDNlQuTbVC4
youtu.be/Z4ge29ZSCt4
youtu.be/2tXkYXIMCeA
youtu.be/gIEa_w2XnHg
youtu.be/G10tuUbfbmk
youtu.be/wF74V-Re13w
youtu.be/HmQflE2VMl4
youtu.be/LBk3nyRnNts
youtu.be/mA_HpJCRrbA
youtu.be/rcCu3Yia6WU
youtu.be/NH6GHsB8uqk
youtu.be/tmp6kJH2OAQ
youtu.be/iXqF7WnkZ3s
youtu.be/YEvj-x--2jE
youtu.be/LRaezHyki98
youtu.be/pHg_lsoBvdM
youtu.be/NSMInq0diQA
youtu.be/HUX-HIfijsU
youtu.be/bSXgfr471-8
youtu.be/c1EU8EaCZ04
youtu.be/e8fiild1_CM
youtu.be/_P2s8_Vcq5w
youtu.be/RkIYjHhFSaM
youtu.be/vQQ-XnLP2n8
youtu.be/DxoyJr3oeo8
youtu.be/Hv60gF164WY
youtu.be/hbizM8dcIlk
youtu.be/6tusRkhFG2o
youtu.be/8fZwE6Sr_9Q
youtu.be/ch3DPlf_JrE
youtu.be/dZ6bKfxI4u4
youtu.be/DCKPpY3Yu8w
youtu.be/rBRqNEBFse4
youtu.be/lbqDuUjm4aU
youtu.be/13lwyiTynqY
youtu.be/wBXp6-Bgdm4
youtu.be/AbaXGXdtNq4
youtu.be/jdtdGvRsGAA
youtu.be/mazGtniYxx8
youtu.be/DF5mpd9I9QA
youtu.be/ZloeLdKk3uA
youtu.be/H0c0yklKydA
youtu.be/rDz4zz9jqv8
youtu.be/j6TMYO5GILI
youtu.be/KdP9HZvwKug
youtu.be/-zhfiWijwQE
youtu.be/E9jSs4JrhMY
youtu.be/0varMsFsHgA
youtu.be/5HZEr9qCBVc
youtu.be/KQb-6yXKBlE
youtu.be/wyZgre1TJVQ
youtu.be/uoC0yqYK6sQ
youtu.be/tL4IOmOJiPE
youtu.be/8HU9HhPmnqQ
youtu.be/LLwIvkVXBYQ
youtu.be/TOV49rluWSI
youtu.be/fZk-BEpRudo
youtu.be/3yvjFSX0TB0
youtu.be/1uRnGgjW0hM
youtu.be/LY0fi3Tyr7c
youtu.be/_mxt5Mav95g
youtu.be/6kJSFvrt3_4
youtu.be/0rUBWIqx0jA
youtu.be/v-KiH9ItEYM
youtu.be/_vG4-8RoWQw
youtu.be/hbp61fOVFaE
youtu.be/wxAkFv6gZVE
youtu.be/5yR0wlrq_h4
youtu.be/-txxAzge6g8
youtu.be/sUS_1HO5Ad0
youtu.be/jPJaKiaSPNM
youtu.be/CCUWdF8iQQw
youtu.be/g3Z7y_SCJh0
youtu.be/azQewc4M6W8
youtu.be/0KBvuBugITs
youtu.be/cd3StH9ST0Q
youtu.be/23I3d0vNPKE
youtu.be/TfKxEd4T0kM
youtu.be/69TWgWi0JMI
youtu.be/6uk0VjRxEow
youtu.be/UNo6LXe4VHM
youtu.be/g-UJN8eiypw
youtu.be/-tTa1N00maY
youtu.be/9G9r0XQ98ns
youtu.be/dW_bQgT5uqg
youtu.be/pd8YvFhNQk8
youtu.be/4shjT601-d0
youtu.be/mNYOqn_za7Y
youtu.be/4PVIxtgwnFQ
youtu.be/oxM8Xz2tYRo
youtu.be/i-uFx0cThfs
youtu.be/hVI-QfGtQOg
youtu.be/puonmb0y4e4
youtu.be/6KLzZRICJYc
youtu.be/yoAGivgTJgc
youtu.be/FwUhrkE38BM
youtu.be/_7T7CnTEXA0
youtu.be/vbY9dgitRnc
youtu.be/W8vztQXLB8Q
youtu.be/sUslkLG1moE
youtu.be/fc62a9fmwzQ
youtu.be/VZYlEtXTtpU
youtu.be/y3oo6J7M4rU
youtu.be/qzoCFxzyUE4
youtu.be/DO2NsSoGBGI
youtu.be/vJflsxW92HI
youtu.be/awA7BnIO9WQ
youtu.be/6N2WiXDGx98
youtu.be/pLFjw0zKcgQ
youtu.be/4mgUuHfQWaQ
youtu.be/Fp5hIn8As20
youtu.be/6rQrO0ce2cQ
youtu.be/0AJ5FKO-VbE
youtu.be/s9Ju9J8noDI
youtu.be/68EDGMr2W9w
youtu.be/oHj0ym16lmQ
youtu.be/o7s9yi2BJac
youtu.be/bgIU-q7b6O8
youtu.be/bnvTo8sLFJo
youtu.be/u0a9PcSqjOI
youtu.be/efmf3vOcxtg
youtu.be/qGGZv5D7Hd8
youtu.be/WjbsD-TYi3s
youtu.be/qy5fntUN0ow
youtu.be/Y7Dec_JdL3c
youtu.be/dtT0V7yNgow
youtu.be/fvNSLPLj_4M
youtu.be/kRdF56UlXs4
youtu.be/Vj-aGNMEiNU
youtu.be/L3MKIS2bRCk
youtu.be/gJyuevQjriQ
youtu.be/UCK0G65Lraw
youtu.be/iRUS2mJmgDk
youtu.be/HjLhTiHflaE
youtu.be/x0rsy7JM5tw
youtu.be/OqqbM1B-mPY
youtu.be/WlIvlSoFHE0
youtu.be/LHW6TpuoKA8
youtu.be/lXHxiKDTHfU
youtu.be/-JotNEGtOF8
youtu.be/HazCWp9hmtY
youtu.be/7uvwWxAHNzE
youtu.be/YI51ePdjBhg
youtu.be/BllWc1BVARc
youtu.be/LyJGijjI2JU
youtu.be/NBPwueQmXmo
youtu.be/beZnfSXa1Ag
youtu.be/z3VMsjbcaBM
youtu.be/6aBFNWjPrHI
youtu.be/ZXMH6DbjyDk
youtu.be/AV9lxspOm-A
youtu.be/oFxU1dMH2E8
youtu.be/18tgLXBceRw
youtu.be/yUsd7Qs4NOk
youtu.be/URaCE3PLwmA
youtu.be/wkvwmUokc8k
youtu.be/ReqGw3YOSWU
youtu.be/PDhXT1Iif9Q
youtu.be/oB3BtJZc7rA
youtu.be/o1BILguJisY
youtu.be/NIBinR2bJA0
youtu.be/4v23p9Oj-7k
youtu.be/LmJ52TcJYbk
youtu.be/4VDQ5GNUuxA
youtu.be/0h1x7tAr0UI
youtu.be/m5oS6lL2VIM
youtu.be/6wIIWhMJHUM
youtu.be/W192fcF6_eU
youtu.be/Umig_alBp90
youtu.be/exMqg9c1wEQ
youtu.be/L6FziT8C-c4
youtu.be/BarpUyDN7sw
youtu.be/JpjieKyOSwc
youtu.be/a1zx3Z9P2fQ
youtu.be/0JKW69WWQOw
youtu.be/twTTeEjJV6s
youtu.be/gcC-08i1AzM
youtu.be/yjbP2gmDqFA
youtu.be/FYtuoNv3dC0
youtu.be/WJ1VxrAyI94
youtu.be/UZqYTXB8oSE
youtu.be/eZBnorqk1vY
youtu.be/0HLxEXIesTc
youtu.be/Ge0BEEbyFoA
youtu.be/HwFfDUle4nU
youtu.be/EHepxUxUpcw
youtu.be/8a1OV0bebCA
youtu.be/T-D3FV2h33o
youtu.be/cQztiu-LqUk
youtu.be/uFkGVkgEfcw
youtu.be/xRZzmwOgquQ
youtu.be/QpUqpLh0iRw
youtu.be/uqaMXUlGWAE
youtu.be/QZbDpDFExdg
youtu.be/_0r3buB3KS8
youtu.be/kg9cIKb9lyw
youtu.be/tfEKNUL4_xY
youtu.be/XBdjU5v74YQ
youtu.be/v7WLfwGChew
youtu.be/PCIotrm9VMw
youtu.be/GkPKt3ux1ws
youtu.be/n2RiFjWSeYw
youtu.be/uUbR2xvX-tE
youtu.be/zp8HVS95-V0
youtu.be/yx15mHKjMZU
youtu.be/-V3g_lFXhU0
youtu.be/9rcSH3sVDoM
youtu.be/u19FOX6eltY
youtu.be/5cBJcV4HPRk
youtu.be/-GMAGLwJFPY
youtu.be/p33fAfTRNuM
youtu.be/b2CSnWPfUNo
youtu.be/6StTOotg4EM
youtu.be/joifAER6VFU
youtu.be/Q5hGtHL8t7M
youtu.be/1eVsu5F67-8
youtu.be/qvAWzRKy5mI
youtu.be/x4teU6DJFWU
youtu.be/ZJJPmBleTvY
youtu.be/ITpcD9X7Izc
youtu.be/2HET7oJ_dso
youtu.be/bZ0tlKBU97E
youtu.be/z3tsZfYAOyI
youtu.be/hu72Lu5FqE4
youtu.be/pYUHG_7t0kY
youtu.be/52fRAzmjJoQ
youtu.be/p4eP0PhAt7A
youtu.be/bhgaYXXDTP8
youtu.be/x5VN2x3WKJU
youtu.be/lm2kD-0rDy8
youtu.be/MDn1TiEKu2M
youtu.be/KsJusDShSSQ
youtu.be/z5i4PE8jZv8
youtu.be/RALwH79Qqxk
youtu.be/KEFdS8O5ES8
youtu.be/i8uKLecQPww
youtu.be/NNv8P2F-zRY
youtu.be/p15-cubKQsM
youtu.be/7BsgACPTOYE
youtu.be/NCAZn5Ie4xk
youtu.be/RrPJW7d245U
youtu.be/aKsv6pZVlFg
youtu.be/fHhFaxdLyBU
youtu.be/tZIKirwnj-w
youtu.be/pV1SXVHl0Ag
youtu.be/PLb2AKWFsCU
youtu.be/XakA50Dp1XM
youtu.be/HaQ_DHYP0-A
youtu.be/ekdKZxbYXCE
youtu.be/Y_OAbv6VWZM
youtu.be/BRmFojn9PBk
youtu.be/5cPdog1ZB48
youtu.be/0Gq_xmEoxG8
youtu.be/XqV_sBytxJc
youtu.be/P5ZVVntIT-E
youtu.be/N9fiYrG9ES4
youtu.be/aeRiKSf3h6E
youtu.be/Dz5iv8BtrPY
youtu.be/jfYdownmrUA
youtu.be/6rkR0IdBblI
youtu.be/PJJ1LJnVjuQ
youtu.be/bUWcmEkZDwA
youtu.be/21RsGfi5ink
youtu.be/vV0CsUZ2y_A
youtu.be/xHYIPhfj8E8
youtu.be/Plbun7v3_oA
youtu.be/TW1P3fdZN04
youtu.be/NcDsY7iXE5k
youtu.be/vx0mgxRuQfk
youtu.be/iM_VlChiDQY
youtu.be/Ls_hirqFJ_4
youtu.be/EtYQW1Ost4g
youtu.be/47jbMRBhLcc
youtu.be/5iONFvC-ypE
youtu.be/M-JnntE0UzY
youtu.be/2YY3vBry9TU
youtu.be/NUhTXLGPNIc
youtu.be/r9ATcVtTyNU
youtu.be/PJsf5QY12rg
youtu.be/9Z2pS5EAPq4
youtu.be/6jDeGYZLzvU
youtu.be/a2UENM8-EfM
youtu.be/3lxDYUkj4f4
youtu.be/Xp5Hu0Kjj-M
youtu.be/JISuO30VJnM
youtu.be/lwPgPlzeEZA
youtu.be/Re7xoNewoPs
youtu.be/95VU_B9Ewq8
youtu.be/fVaXeCLY45I
youtu.be/kSOkmOqnteU
youtu.be/ouzKl0oD6sU
youtu.be/Adk2z5NwOfc
youtu.be/B0db-F1B5Qo
youtu.be/oWu3PojHC3s
youtu.be/P3rw4YBN4wQ
youtu.be/83NtUIlv-Oo
youtu.be/_Wn_qevWy6U
youtu.be/bijQ7BEmfuo
youtu.be/htJkcefw0Q8
youtu.be/zt1h-c6GNvU
youtu.be/Qx11bobE_XI
youtu.be/aomd1Pjt61A
youtu.be/O4Y6NlxhZRE
youtu.be/q9T5pzFm9Ck
youtu.be/XHk5ctS6Htc
youtu.be/9_z7ni9Kre4
youtu.be/BoqjKqt__tI
youtu.be/27bwB6WLY8A
youtu.be/CQG2OkYscQg
youtu.be/9FEaUAlk3fo
youtu.be/5BcmsuiNLK4
youtu.be/3BLdEFdQh9g
youtu.be/n23uWG1lf-I
youtu.be/rbsfynApnVg
youtu.be/YoYlI6akAbk
youtu.be/B54x-qPdIfI
youtu.be/V3erPQQNT_E
youtu.be/rMhwlWtAMeo
youtu.be/ARI_DnVlZF0
youtu.be/5Id3BmSvAgU
youtu.be/DBt3qQRuOxY
youtu.be/UYSMm0Oj5HU
youtu.be/vDT-Yj5n6zE
youtu.be/dKHwymo7iYg
youtu.be/B8BdiUsSVIU
youtu.be/6rgxQMgw4bA
youtu.be/G_gJWjW-f3I
youtu.be/-YwagEWvE78
youtu.be/daaBnWi01N0
youtu.be/TYuDoau6ttk
youtu.be/_-UGt5iq3JM
youtu.be/Kfx0axlCHVs
youtu.be/Dxo_P8jnlc0
youtu.be/hQHfEolE-q4
youtu.be/2QCgX8lZr0M
youtu.be/y366nl3zMXI
youtu.be/r09cDPsQ1wI
youtu.be/lxjRSH6LvQ8
youtu.be/zpz1frvjze8
youtu.be/qaqZJ0JSWy4
youtu.be/-7-eraQL92c
youtu.be/q1vlKjmqZx4
youtu.be/6psMt5EmyBU
youtu.be/kG7Ktw3Lanc
youtu.be/d1zq0C28KPk
youtu.be/jyn5VeFdyNY
youtu.be/m8Baf9RaSQc

In [10]:
df_crime2 = df_crime[df_crime["text"].str.contains("diddy")]
for index, row in df_crime2.iterrows():
    print("youtu.be/"+row["video_id"])

youtu.be/2SD2bGzrVyU
youtu.be/4d3VAQRRCGQ
youtu.be/hT8nxsVAc54
youtu.be/b8V7OneFLnc
youtu.be/xoldyDQNBXg
youtu.be/nlTnomJz5DA
youtu.be/FeHov4HLo8M
youtu.be/AKoLj7MoVpo
youtu.be/CDQYRnAwpxk
youtu.be/iwv8CtpRrWU
youtu.be/RPmkRjCEmjE
youtu.be/ArPFc2m6Iy8
youtu.be/kuSmgqzcc7M
youtu.be/8pQBHuA-oXY
youtu.be/INdHo3NcBQM
youtu.be/E3QGJmcT3L0
youtu.be/jf4ZrJr8HGY
youtu.be/4ysP9ORbDss
youtu.be/qO3BkynqX8g
youtu.be/LLezY3KzGJY
youtu.be/j3YUIWcNtGs
youtu.be/701rN3-makc
youtu.be/EssDs0LKOcg
youtu.be/P68sp1X9upI
youtu.be/GJV9kWdOiW8
youtu.be/oruLIfmf2AQ
youtu.be/1YYVywapjKI
youtu.be/9Ninmnm-vN4
youtu.be/enspKbIW0NA
youtu.be/KMTEh-nNyBY
youtu.be/waXHhw-I9aw
youtu.be/DMxTUHyEhf8
youtu.be/YQjPWZuqDOU
youtu.be/I-9rCMBMh-8
youtu.be/MXwoz7XKzt4
youtu.be/_kPIeeBCY2I
youtu.be/0HaEUyiUwJU
youtu.be/l1hYlvjz67A
youtu.be/E6L4sP7Gras
youtu.be/X3j8-RF75P4
youtu.be/dkuINe_mIHQ
youtu.be/wWAuNoLQXOQ
youtu.be/lyqgFqcGAHY
youtu.be/F1Q9A-ylrS0
youtu.be/qQ2CbLzOtmw
youtu.be/wsd3_MxpRns
youtu.be/C_dTKA7EdtE
youtu.be/i44CohoU6e8
youtu.be/o07CIrbrhMM
youtu.be/KqNqOjRlkgs
youtu.be/TQVGKCEgXoc
youtu.be/IUpgEgTf1Bo
youtu.be/uv-t8Ltkx6A
youtu.be/xL38ARCbRwU
youtu.be/erEBP8Q6Cu0
youtu.be/b0WpZREc1s0
youtu.be/MMttMeBxIvs
youtu.be/anBof7abywM
youtu.be/jqKjO7c7vq4
youtu.be/bSXgfr471-8
youtu.be/dZ6bKfxI4u4
youtu.be/rBRqNEBFse4
youtu.be/13lwyiTynqY
youtu.be/TOV49rluWSI
youtu.be/_vG4-8RoWQw
youtu.be/9G9r0XQ98ns
youtu.be/4shjT601-d0
youtu.be/W8vztQXLB8Q
youtu.be/UCK0G65Lraw
youtu.be/ReqGw3YOSWU
youtu.be/PDhXT1Iif9Q
youtu.be/oB3BtJZc7rA
youtu.be/Umig_alBp90
youtu.be/UZqYTXB8oSE
youtu.be/kg9cIKb9lyw
youtu.be/XBdjU5v74YQ
youtu.be/-GMAGLwJFPY
youtu.be/b2CSnWPfUNo
youtu.be/NCAZn5Ie4xk
youtu.be/XakA50Dp1XM
youtu.be/NcDsY7iXE5k
youtu.be/Qx11bobE_XI
youtu.be/q9T5pzFm9Ck
youtu.be/B54x-qPdIfI
youtu.be/DBt3qQRuOxY
youtu.be/B8BdiUsSVIU
youtu.be/nnOB_4twtXs
youtu.be/2Og1hZNiAU4
youtu.be/EWB5_CULZHk
youtu.be/6fZLo2E5oZg
youtu.be/FEW2FFaPqUA
youtu.be/SOC9I_rludM
youtu.be/YsFbCJmuCxM
youtu.be/aZ-dXK6qau4
youtu.be/tb7cIhKxIZE
youtu.be/B0DKFe-2WPA
youtu.be/b9Vnun60QLM
youtu.be/l-06MyZ04VY
youtu.be/LdL00ap1M5Q
youtu.be/GcuofFOkFks
youtu.be/SyF_lO3GdvM
youtu.be/zVR9cNe1nAk
youtu.be/BkEoG2YkU_0
youtu.be/K1E3t5FueDs
youtu.be/wukarAztc5E
youtu.be/8y-wSxIDfgM
youtu.be/tks3oKprEJ4
youtu.be/YnvoN9ZhYWE
youtu.be/cEYtU98Rjn0
youtu.be/E-SfNutEI_Y
youtu.be/UI1DVrmmvcg
youtu.be/GRt2pH9OZLU
youtu.be/Iah6mT67sgo
youtu.be/UirpIR914a4
youtu.be/IoJLAArQolU
youtu.be/mFygv52cUgY
youtu.be/BnjEs18DVvg
youtu.be/qrabeFSg_VE
youtu.be/FARv3F5Rc2A
youtu.be/9r20tNHivKU
youtu.be/zwZIbivc1h4
youtu.be/T6nFKA0Jj58
youtu.be/GSsR2OB3knM
youtu.be/XkGUI_qVNTo
youtu.be/HHElQWB45AU
youtu.be/P0Qcevf3tRE
youtu.be/NmLIQ2BGMLU
youtu.be/yyn3LKhLLOk
youtu.be/n1cMZXX2EKg
youtu.be/ku-vvxtBRlA
youtu.be/FvcFv40s58c
youtu.be/InLmtwVNnmk
youtu.be/FiljOkmV2-8
youtu.be/4I9pw24HHwg
youtu.be/4E03buR5rSw
youtu.be/ZCMAVGg9NDw
youtu.be/7KgcUDpNWb4
youtu.be/K6TLIXuBVts
youtu.be/55UFvn4Qa-A
youtu.be/lJ-ZulDuhpE
youtu.be/otohbyEeEVM
youtu.be/p8RFW0G9Duw
youtu.be/aUYyHhyaNiQ
youtu.be/ZCrr1P5WYfQ
youtu.be/WH9w9hfBxUg
youtu.be/qpPADIUKjbg
youtu.be/daXwn8NcWG8
youtu.be/YTOs4C71pHg
youtu.be/2iBavrFB5N4
youtu.be/7kmc5gh-T7k
youtu.be/p9SuMGPWLyo
youtu.be/uK5WJGJNz7U
youtu.be/MgBzahslwbc
youtu.be/EmsaC9nApPw
youtu.be/3jkfayYxy14
youtu.be/ml0lG9mwcsE
youtu.be/PMWGlolF-Rc
youtu.be/gzUPzpTA1rM
youtu.be/wVVu65Bp2d4
youtu.be/sowJ60wofPs
youtu.be/JkbG9gNPzt4
youtu.be/a9ZSFjM3MWo
youtu.be/8z1h7hZQmIQ
youtu.be/CnF3hqmtolU
youtu.be/HdOHSj7cfwo
youtu.be/czxBQ03GdZw
youtu.be/Gk6mfKy9D7E
youtu.be/gU309I7rb4o
youtu.be/ebhkmoL07Ww
youtu.be/siSNJrAvvvQ
youtu.be/vVf_8mUJc_4
youtu.be/9G9RVEt9LS0
youtu.be/1UingsUi0mI
youtu.be/PhhSPFoOOII
youtu.be/V1xSQZCzTjU
youtu.be/EpkwrnruYd8
youtu.be/fmbOEHAjQ-k
youtu.be/VKjrCH74ZBQ
youtu.be/n_azN_FGD1Q
youtu.be/lWWcRppVmcc
youtu.be/2ZUx2GlUyHU
youtu.be/Iw_zkLqBNGA
youtu.be/kUpbbhbfZbE
youtu.be/Wvpw_nrJX_M
youtu.be/3lEwfsgXXxE
youtu.be/7BZPIeMaKb0
youtu.be/GoRxHjJfVJw
youtu.be/vMIfsESI8Rg
youtu.be/3J1dnE123g0
youtu.be/_uOZ_283tlU
youtu.be/e53Xdu5K-CQ
youtu.be/sOEr8IGDc0c
youtu.be/IALu7GhPYXc
youtu.be/hGrm0zIg8IE
youtu.be/oji6yAPX2_8
youtu.be/W-0ZQTUt4G0
youtu.be/dfrxe1qzbOM
youtu.be/pIXXKpoFrgE
youtu.be/kcPt9JjRxPI
youtu.be/JHzEY2PBkxo
youtu.be/RgSNjE_1rV0
youtu.be/vSF43_g0fqo
youtu.be/naY2RTt-wQE
youtu.be/4cN4uJshZxg
youtu.be/61aZN2CUI_4
youtu.be/VFMoDJICY4Y
youtu.be/8YGKirXFaA8
youtu.be/79XZBFoYD8c
youtu.be/iOBfg8Q0i2A
youtu.be/oK8b0hMuuxg
youtu.be/ofpBPKXPIAk
youtu.be/XzD-bzauH_Y
youtu.be/w2m5jf1u1ZA
youtu.be/le48SNEN_2c
youtu.be/o-E_jQpNEqw
youtu.be/exvbyKIieus
youtu.be/sFN1wNPvzPQ
youtu.be/ujhin-FGZeA
youtu.be/0bWDNXc2hQQ
youtu.be/5PcyI20vtzc
youtu.be/N7Xop_lnFjk
youtu.be/_gJFHY6eu0A
youtu.be/Ls779oB2fYM
youtu.be/WgoC6DKznEA
youtu.be/e7pgXv_TmWc
youtu.be/PNusg5ulNjM
youtu.be/cb0TVv2Zhdk
youtu.be/MJ7Jo7aRHrA
youtu.be/4R7juv00YrM
youtu.be/Uf0fuon0TIc
youtu.be/J2hwbF7Ib7w
youtu.be/xYtU7PXPj54
youtu.be/D_8X3Ge58sg
youtu.be/DGiaKB4Y8wM
youtu.be/YBDpJs4QfLY
youtu.be/q1FXwNcJdmA
youtu.be/m9XTVZmu-Fk
youtu.be/uXdBnwBp3DE
youtu.be/K1shHJQVOjA
youtu.be/uIRWuZCCGU4
youtu.be/ZompvsXwkqU
youtu.be/uCLbeknnvNo
youtu.be/oa_D4kk72BY
youtu.be/EVOxnix8Ne8
youtu.be/T0EDCAVsEDM
youtu.be/K3O9ElTvWYg
youtu.be/70fjFfh-E50
youtu.be/U2Q7jk-9eSg
youtu.be/U0DTERPrwlw
youtu.be/TmXE4qMi2tI
youtu.be/JQ9KmTdcUr4
youtu.be/c9UQTfaxPnc
youtu.be/BPbuMcFOCWo
youtu.be/S8xVo7Scv-Q
youtu.be/JH_HxSePdRQ
youtu.be/RRxDq8ScA08
youtu.be/kNrDW_FiAlc
youtu.be/WTwqL1pCz9o
youtu.be/k_z2IN-qMm0
youtu.be/DQRKeXQuR2M
youtu.be/G15RaO3Wgt4
youtu.be/P_mC4JfV0eE
youtu.be/DjWJ06ec-I0
youtu.be/GEp4r-evYoI
youtu.be/CDkDTEBrrzw
youtu.be/BA6Qdy_GBNU
youtu.be/NiSFkOrqdYo
youtu.be/044ZZGZgbeU
youtu.be/rHyhYLISvWE
youtu.be/5qqG9TSZyFg
youtu.be/zetu713nZ2I
youtu.be/FLLYlTovOZY
youtu.be/eSqw5hvTCr8
youtu.be/pSnGxDj6kQI
youtu.be/gIRHH4nHVEs
youtu.be/coN_tWi-Gc8
youtu.be/DA89qav2F-g
youtu.be/5PBXahosERs
youtu.be/ng571xyGHgU
youtu.be/egBEO8bSvXA
youtu.be/aB216XWg3Us
youtu.be/jqjSofi48Fk
youtu.be/rsI1bD2_uvI
youtu.be/8n0aeAJWEYY
youtu.be/5aKTvsMw3X0
youtu.be/GjV7TOXxo-U
youtu.be/bJbzdUX79M4
youtu.be/vGksMUmctCI
youtu.be/NKCSj5T4Yy8
youtu.be/A1DZCqu595c
youtu.be/6QBBOF5kkys
youtu.be/D_4W-Z66w6k
youtu.be/xai35U9vo3Y
youtu.be/HoInswAbyDE
youtu.be/HM8-vMtoj0w
youtu.be/pAMDEEjZu24
youtu.be/X2AyWjImI5c
youtu.be/WZ6SwcdKX2E
youtu.be/kvii8CZtWY4
youtu.be/JGor7ZyCawI
youtu.be/bhW9GTh4EUQ
youtu.be/J65QYpSigqk
youtu.be/iB8ZhGmjQoQ
youtu.be/K30JM2M9KH0
youtu.be/xHdqk5Q-yOc
youtu.be/b9C9OfZHdi8
youtu.be/ILSSVF4Yzig
youtu.be/3VtPcTxzXiA
youtu.be/ce8rAcUxqk0
youtu.be/F8TRP5PE5l4
youtu.be/qKIfk7yGuWY
youtu.be/xXeyEFv6agE
youtu.be/AbiZU_1mqZs
youtu.be/VIw62pRdwn8
youtu.be/nySlLwrAfLI
youtu.be/4Q509dyCu7U
youtu.be/jgxbdqkvbPE
youtu.be/iL_mmRT6x64
youtu.be/e7FpJYDPD_0
youtu.be/4F5_DV1KpT0
youtu.be/GeEhe15bj3o
youtu.be/uwDCtXU1dlk
youtu.be/ORoyUtrYHPI
youtu.be/LmdXBY1EA7A
youtu.be/FO-g75Hbqz0
youtu.be/XJahUD-GIVw
youtu.be/YlyYfRpHFEs
youtu.be/VfAryL0yGXU
youtu.be/UVZxlDVRZ5Q
youtu.be/gRzRbJlEIm4
youtu.be/ValNDO5er4g
youtu.be/A-gYhoko0AA
youtu.be/NBWMOxgFfcM
youtu.be/hbhKS2QZb54
youtu.be/HGn7u0yAZYM
youtu.be/-KS6Viw-uhA
youtu.be/TgcHCoLN4to
youtu.be/Cwl69729o5w
youtu.be/BKjJOqHqUEE
youtu.be/5EahiGXpfNQ
youtu.be/yVQj-ZKpeAc
youtu.be/zZTXf_VnTfY
youtu.be/oOdZdlkxOHo
youtu.be/WnvxT06nvug
youtu.be/FMV1Bb1aRqc
youtu.be/eymQ9HpA2ms
youtu.be/MfpesKGvZfs
youtu.be/HGvHnUxI3dw
youtu.be/-jMl1ymqxxA
youtu.be/IrPqoWA6Kj8
youtu.be/oBguN6RViPs
youtu.be/J5DR7azsV-c
youtu.be/cbdt88e84VE
youtu.be/quRdOfmIDg0
youtu.be/gctVKpEXvWQ
youtu.be/M3Nj3v63dl8
youtu.be/4Hlg3bLRcXA
youtu.be/f6nifBcQiKI
youtu.be/-Ysd414nIiE
youtu.be/Cr8ufCPya8s
youtu.be/2vI1uyGZPCI
youtu.be/DfbOggc5JBc
youtu.be/-LDXFMSgSk0
youtu.be/-Vf1dh41Zeg
youtu.be/TdmSTJ7_GxU
youtu.be/hCzlSuy4MaI
youtu.be/lQ1UmjwxdAQ
youtu.be/6X0d6N8n_fQ
youtu.be/smbJpjB3To4
youtu.be/8_8Hk_mWb0E
youtu.be/nvcyajxZ3LM
youtu.be/3Mt-dkqlB4Q
youtu.be/NFT8gDgRVkM
youtu.be/8JAn92SVI3Q
youtu.be/LsFK4wsAI10
youtu.be/ACmj1p4aGHk
youtu.be/sTcWqjJBmag
youtu.be/LohivBYasXM
youtu.be/D1Wl-9KOaFg
youtu.be/xULfwc9rTNo
youtu.be/5DiCz6MfE0o
youtu.be/U3weq3uHUmg
youtu.be/-UuT5e7a9uc
youtu.be/JFI8q7Xh1-A
youtu.be/7SCGdx1wdPA
youtu.be/oFJXxs6kyW0
youtu.be/vGWqwCtxFT8
youtu.be/honswplA6RQ
youtu.be/YHTxFqjLPVM
youtu.be/tzmTeVtZbzw
youtu.be/zWM80SK267s
youtu.be/y0KN3bS13f4
youtu.be/vcikukicghc
youtu.be/hP9u5gtnmS0
youtu.be/1ccLKzygCH4
youtu.be/I1kuUpf_g0E
youtu.be/N28OZQqEoEI
youtu.be/YKTM3uXXukI
youtu.be/zJJhMOIxUy8
youtu.be/HNt5D3Z0EAM
youtu.be/EmSvrUeM0sk
youtu.be/8ZX2dPr74eQ
youtu.be/fEBGLOVVniA
youtu.be/JpHXtl3PCJk
youtu.be/pEDdtnzDDVQ
youtu.be/0RIh248wF5Q
youtu.be/RCcFbEuLm08
youtu.be/5KOB4bZMXNI
youtu.be/VGUiL1Bg_jI
youtu.be/Sz3mS7IVOsY
youtu.be/xrRY2e5ficQ
youtu.be/n_wIzIlc1qM
youtu.be/w0Y1TaTQx7Y
youtu.be/UQaKf5FGjW4
youtu.be/h0ZgB5JOIGQ
youtu.be/xD6kIRtX1T4
youtu.be/r0421SczE1c
youtu.be/uEZsXzx_FOc
youtu.be/F8VlTkTwu5w
youtu.be/bLuXnavbixA
youtu.be/I5EAbaTsvLc
youtu.be/BQzPBB-Wae8
youtu.be/mFYkZn5j_5U
youtu.be/1duBZ-votlo
youtu.be/i9SZHqtZ4OM
youtu.be/IeQ7HDq4o6E
youtu.be/QngNPb6KE90
youtu.be/CEKbIMpfHwk
youtu.be/SdbWU9LfeGk
youtu.be/84CP3UR2YE0
youtu.be/a6zsn2BMj_g
youtu.be/deAd1FyRUoU
youtu.be/vb1RTOHOQS0
youtu.be/z9Rtx7sBDbs
youtu.be/pikBvKUtB1I
youtu.be/8cyc29GwI68
youtu.be/xZL-V7iQ9lg
youtu.be/EKIN_u8aCDU
youtu.be/aQl0TK1lDog
youtu.be/HTG-23ih5A0
youtu.be/rvtPKKH6Fns
youtu.be/mMzQE2ldKfI
youtu.be/dBb__4fYSaI
youtu.be/3VrM-QVjtgM
youtu.be/4iWTalbYf_E
youtu.be/KxPaCscHp-8
youtu.be/K0T8Wrs28VI
youtu.be/bYnLD261FfQ
youtu.be/3pNEPUJhwiI
youtu.be/mGg9EAyhqOM
youtu.be/r6Y5uQqcv2Y
youtu.be/hNjkEeEoIwY
youtu.be/2H3AH3KKZwo
youtu.be/f4PI5lsfRsE
youtu.be/6WvU4cCmyvg
youtu.be/C-Y5PI-uDFY
youtu.be/Tv6-aGX8wxA
youtu.be/x7RPR8-aCG4
youtu.be/WW6jrg4f_y4
youtu.be/CwSh3bqq72c
youtu.be/j8G-iISiNl0
youtu.be/kglX4xtbY2Y
youtu.be/xCve_qHcLuM
youtu.be/VG6YpRT9WEE
youtu.be/O6dUuCcPAZo
youtu.be/hDnJAq7xnt8
youtu.be/YEzb5v_ENXU
youtu.be/JfDNkhuxutA
youtu.be/cpI_0NNBj7Q
youtu.be/SUTEgzQEPJ0
youtu.be/or0WCokWL60
youtu.be/iYqqzaoLb7M
youtu.be/pxW488QXNmc
youtu.be/LkJeqCIluJo
youtu.be/6FUUj1MpTKc
youtu.be/7NixE63NakM
youtu.be/qGx0yFii9Y8
youtu.be/VisEFMpX5wo
youtu.be/kQwpMrVH7W4
youtu.be/ZbBYKoxu3Fk
youtu.be/t34nzJu2PH8
youtu.be/obZ12ATDfBI
youtu.be/Prvu1vINFTg
youtu.be/pUZMK1g9708
youtu.be/93yJGv-1oz0
youtu.be/KeunnjrZkok
youtu.be/b_5zJRhTD8Y
youtu.be/YUR3GQJL9ss
youtu.be/d6n5XeX5vyc
youtu.be/ZU7PYiAANNo
youtu.be/8YIzr8PTXQk
youtu.be/igd4Lc2-UCM
youtu.be/Sy_M7xlwhiA
youtu.be/Wz7H8skGcF0
youtu.be/Bplh0hrvnnA
youtu.be/LamiXPMUQ2U
youtu.be/jw8NnP3w014
youtu.be/P9l9e_KrD-I
youtu.be/7V01aCwWvRE
youtu.be/Zj11-8-p384
youtu.be/CxoyX2nIaQw
youtu.be/cYPf8C6Xfg8
youtu.be/G2VTrqqmIFA
youtu.be/Fc1-Ci8PnTo
youtu.be/JL0r0aW3X98
youtu.be/YcZuV4Xy8k0
youtu.be/FwdNoVnht4k
youtu.be/LCkCiXXByZ8
youtu.be/mi0nXqZm-6c
youtu.be/9tI0AFpgvxQ
youtu.be/c8Ctwtj3Bgk
youtu.be/CCH758FuOiY
youtu.be/WJhAkzjuSug
youtu.be/Gh1BCVzDGgU
youtu.be/UrZy6WT4FP4
youtu.be/xIcgvONezks
youtu.be/haXDU9V3Vjc
youtu.be/vWscGeA-tuE
youtu.be/mMojh7OXg8g
youtu.be/Er_1wSbFVAQ
youtu.be/f7wR4xx6G4M
youtu.be/w3w316ALdLk
youtu.be/Hsnnaha4jNg
youtu.be/2duFOYCzFrk
youtu.be/hjrbB_X9brc
youtu.be/q7pJJJOGkjE
youtu.be/6Hg0cxz9TLE
youtu.be/7JBjIzLvnSg
youtu.be/bw-_sdmb77Q
youtu.be/Crhb189F6N4
youtu.be/hT87RTK6MtA
youtu.be/ydajAjL9Ufs
youtu.be/r4M7YlZmAlo
youtu.be/jRGLA6X5nhs
youtu.be/DUKHeccDEE0
youtu.be/ZItSRZcioP0
youtu.be/P-oV0o31gQk
youtu.be/wBbf3c0P_fc
youtu.be/YnUorRTVf4A
youtu.be/oDMoC6O0Ow8
youtu.be/GjYoqjx0jHg
youtu.be/BU_xZJPVYVA
youtu.be/Zfo_ncg9ZSM
youtu.be/ehIcXDpmz2s
youtu.be/PlgiB8Jx8-k
youtu.be/haW4tZhoiLM
youtu.be/TQuTd-hncUU
youtu.be/2xyCZFgydOk
youtu.be/xckBVe7MUfc
youtu.be/ZR5yhKQo3dc
youtu.be/VgCeUbblZOI
youtu.be/NQntLqIJVMY
youtu.be/ZXDxbW17KBk
youtu.be/-DFtTuAGwhA
youtu.be/xgwqeBHIUDE
youtu.be/hcVgpEYwOuM
youtu.be/NR34zrLBnPw
youtu.be/uEc-9IacHxQ
youtu.be/eEnSavgLdcE
youtu.be/QVod9z4UeXo
youtu.be/WkSJdYpOw0I
youtu.be/lQsngQ3P7FM
youtu.be/QRQS5a0XsnI
youtu.be/SWbEJYixUY0
youtu.be/kt0GiOUQnNs
youtu.be/AisY1nbNykE
youtu.be/WiZrWCkYHpc
youtu.be/995fd1O0HFM
youtu.be/bPXlKI0KHks
youtu.be/SnBgB3gXldU
youtu.be/QAJb_Gkuhl4
youtu.be/lpi-05nSTWA
youtu.be/9dw8d6HY1jw
youtu.be/i42No8SRjzs
youtu.be/g4R5rHMjySc
youtu.be/gk9QkdF1ajI
youtu.be/UN9-MvYuit0
youtu.be/A6_CxLEE6YA
youtu.be/M47uLccdkz8
youtu.be/kIpK4aVrUWA
youtu.be/8hQ3zDbshZ4
youtu.be/vdctDQsDaCk
youtu.be/054mV13VpDQ
youtu.be/2magXCdfMHc
youtu.be/bjQ3GLTQZeQ
youtu.be/ziANmjkImt4
youtu.be/EaIoUQeE89c
youtu.be/YrQCAkSaUrQ
youtu.be/xSLZZ4dmKSs
youtu.be/YJJt4SIHX84
youtu.be/zLEODNKQWwE
youtu.be/M3Z4zv-0HTQ
youtu.be/sQKUglRPEK4
youtu.be/MnMffD6938Q
youtu.be/7vQHruL0t8Y
youtu.be/3mgL0JIhWds
youtu.be/tNOwtgwpE4M
youtu.be/U0B_2A_X-s0
youtu.be/W2TN_NHPnS4
youtu.be/VqgaFMcoukQ
youtu.be/CSV68R0eQ_o
youtu.be/-V4gtnMRoqg
youtu.be/69UsS7ecWbg
youtu.be/-5ZypHaRWqk
youtu.be/co4U9LJslGo
youtu.be/j46jE-VRLzk
youtu.be/MBYHu9O4ZQ0
youtu.be/O5G-9eLGZ-U
youtu.be/rtN_gkL7T8Q
youtu.be/vRB7U4NzR6E
youtu.be/8MalStzntPU
youtu.be/A_I7Mr4czmU
youtu.be/nECDKYDHlNo
youtu.be/-M5VR1vhl4E
youtu.be/0-8P9I_nTKI
youtu.be/GLDMut27tNA
youtu.be/YvuwJmTKBUw
youtu.be/6fzc0ajmyAw
youtu.be/Gze-y4c9xFI
youtu.be/BUPVIKiMp2M
youtu.be/5fja1HR7_bw
youtu.be/ygUYssgvZRQ
youtu.be/uGplxNK8Qu4
youtu.be/TyFVOn33mkg
youtu.be/dYTzpGx6HxI
youtu.be/7dlYGGPwxXw
youtu.be/q2qzj2Bq030
youtu.be/KsUfe3Wm5Cw
youtu.be/iCaL8953cLE
youtu.be/USXSdo0MD1c
youtu.be/ACCvSRusQFM
youtu.be/OroY72NbsvY
youtu.be/EKumWgHZ7Hk
youtu.be/5BcZuOSul9c
youtu.be/oYp7vKiLvFw
youtu.be/jbU9t5KH8pA
youtu.be/BBt4EDBWJuo
youtu.be/UMyLXuciHIw
youtu.be/eXlmwdXDT8Y
youtu.be/9kCUYOF8b9s
youtu.be/d5U9GKPUeUo
youtu.be/nJ_YPxGCXcg
youtu.be/A3DMczvazvs
youtu.be/CJUnHBJorPI
youtu.be/9kpQ5k0kWq8
youtu.be/QfzBpaC_EpE
youtu.be/VYr7doCwG4Q
youtu.be/597k9sTSrB8
youtu.be/cp1d54OlCVM
youtu.be/BBZo-VfCoXA
youtu.be/1wN6isRi30w
youtu.be/maJLDwG9qcs
youtu.be/zcuHof2gNBY
youtu.be/TA1HpncKMaY
youtu.be/M-RaIjssDqM
youtu.be/Ioezxz8ndCU
youtu.be/5SXCD5vydmw
youtu.be/VfXzgIFyH5U
youtu.be/2lGIQxWLo7I
youtu.be/EPt4zZ2lADk
youtu.be/h5T_WIzg2tw
youtu.be/2mkjWvGB8qk
youtu.be/2OmciBaVp80
youtu.be/l-BiHeSqyLY
youtu.be/P5aleyQ_mGA
youtu.be/goXeRXZq65U
youtu.be/2lhHakYX5Fc
youtu.be/J7F67Fc0gNU
youtu.be/0VxwgiL9v4s
youtu.be/RoYJkDsJcHY
youtu.be/9RqA9MjKbfM
youtu.be/ychqMZuQLtw
youtu.be/Skgos6Z4RZg
youtu.be/FHKhj_T4c_E
youtu.be/2WmV7kaxz6I
youtu.be/qRy2bSldSa8
youtu.be/r_2XZHi2DAQ
youtu.be/JdkqjhJKu18
youtu.be/cZhPNcRewTg
youtu.be/qZmAybqXGn0
youtu.be/Kfd_6xoJ9Es
youtu.be/cmlfX7QJilM
youtu.be/D2nhXoR_nAY
youtu.be/rAIIZ5IBxng
youtu.be/6XWjKyLdTOw
youtu.be/EThwQP1OP2k
youtu.be/UW0nTzgPi1E
youtu.be/C6LBcPdYojE
youtu.be/Xz6gmanr5g8
youtu.be/SRSW-lhEb1s
youtu.be/jhTiOQlVILs
youtu.be/i8DVIaujdDI
youtu.be/zXPAalYrZ5s
youtu.be/tu1xsYYdnFE
youtu.be/XxhM8HBeooE
youtu.be/WCNCRXhCI_M
youtu.be/sXPI98ivPs4
youtu.be/SANWikO2fI0
youtu.be/2OCZtzD7pBg
youtu.be/eln1_XA_YCw
youtu.be/dSDhFupBTBY
youtu.be/hDa9drmVy9I
youtu.be/r7yKdIrSC2s
youtu.be/x0UdbqVEQUU
youtu.be/1yWVdMSefqc
youtu.be/DKbhVCxeYN4
youtu.be/xMb_GjY7eNw
youtu.be/RRq5sj0QVkc
youtu.be/HvUS002Nrik
youtu.be/rJ7dAfn-0hE
youtu.be/dBq-rzYQ0ZY
youtu.be/9e2GWgcOuoE
youtu.be/F7XxuRexiog
youtu.be/GcB0ZvkCNT8
youtu.be/iIYjW4d6lmo
youtu.be/yFkENEu8SlE
youtu.be/l3SZWOnz5YU
youtu.be/x_KgM7MbnhM
youtu.be/_3xBTWU9g3s
youtu.be/zsPN2oW4lfM
youtu.be/iKnJp8OSQjU
youtu.be/1YMhCjneq5U
youtu.be/g3y8CJoIjQQ
youtu.be/GokW7Ou0Xx4
youtu.be/EpKc2aCWy2k
youtu.be/VtK-wKSsLIw
youtu.be/geTR_06cLYM
youtu.be/ZZoYTHrgkHI
youtu.be/IM_HbkJNoiU
youtu.be/fmeOZR1P29A
youtu.be/_KHXAMP55IE
youtu.be/TTDwChThTMA
youtu.be/3n1H8DpzGZw
youtu.be/JTolctZLxdE
youtu.be/nIRhc2qLYPY
youtu.be/mo6dYsyQVmI
youtu.be/y3WiTiEGoTk
youtu.be/x_1w9khERjg
youtu.be/yZwWSkO8YrQ
youtu.be/KKYZC3N30xA
youtu.be/NvQe9KAjXH4
youtu.be/VfYQLOjdcIg
youtu.be/0aUcQfTvtLc
youtu.be/1wQ2j_vvnyw
youtu.be/GHP2Q2Ke7Nc
youtu.be/K1o27KQS7HA
youtu.be/XE-b5uBAtM4
youtu.be/bhKKy9Mcec0
youtu.be/mzjGzkusCmo
youtu.be/JlJHcNEfj9k
youtu.be/R2-Hg7ce3So
youtu.be/VwzkVVGo0zw
youtu.be/x2TQpncswvQ
youtu.be/iOu3XaYFPvs
youtu.be/FEnxVK5RRb8
youtu.be/tR0XirebRIs
youtu.be/83MXVXlCRss
youtu.be/aw0a7yqw44Y
youtu.be/DOplTM0GRo8
youtu.be/kpFNUPFRW_o
youtu.be/lU3jMBB6SPg
youtu.be/MS8rHcjMmlQ
youtu.be/mgRYui-l4BI
youtu.be/8EYu2oviveU
youtu.be/n9a7jY9WMmo
youtu.be/MeNWRHRgXwU
youtu.be/hI2aLNjXTCo
youtu.be/jXTIKAEMBU8
youtu.be/7fuRYnIPfFk
youtu.be/CDEwRyCuqBs
youtu.be/iz81hU9YAI0
youtu.be/5toZbgRelYc
youtu.be/9pnxC2wu_CA
youtu.be/QH4CrXHXZTM
youtu.be/hIQ9DYxbNw0
youtu.be/7dzsZOcBOhQ
youtu.be/ECO9Oixn0sI
youtu.be/_WVTZsM5_XM
youtu.be/nQeznF0ZvH8
youtu.be/OyDJtiJMggw
youtu.be/9z3oJytbNRo
youtu.be/GFDBxSHZazQ
youtu.be/ROejbnUfpl0
youtu.be/F414FD1Weq4
youtu.be/OPcenQ56DwI
youtu.be/aj_Bx8VqyuY
youtu.be/Wfb5XCT0oSE
youtu.be/o7B_1bZopyU
youtu.be/97ACRlikFt0
youtu.be/Y5LfNsehxaQ
youtu.be/FzGO8Dry7a0
youtu.be/rRc1AmRvafE
youtu.be/IWFFtWELNG4
youtu.be/iwBJLYLoJY0
youtu.be/vg9JsDPU3Wc
youtu.be/yoRt7iXdZcI
youtu.be/y64WQXn1Msg
youtu.be/MPEpTL81L-A
youtu.be/0JzvEvsNMwI
youtu.be/k0t-TzYIjyw
youtu.be/eb9kJ9w-Shs
youtu.be/edBENTiGWEY
youtu.be/jA7rLRE6W9A
youtu.be/nqTze9xlVs0
youtu.be/ZRguU6hJDGE
youtu.be/Dz9kEncnM4E
youtu.be/ZkuNTDfnHAg
youtu.be/HvRVJtq_c0U
youtu.be/QWeTv8hrx70
youtu.be/27qqSVzenEk
youtu.be/Ssv9ZSsNykI
youtu.be/5GEwrPEPjnU
youtu.be/mcH8aTXer58
youtu.be/7JeLzssqxQ8
youtu.be/K7nO7DkmZnA
youtu.be/-1EBxvlNzuU
youtu.be/qGuu-AQ7idg
youtu.be/4H3A45Im9JE
youtu.be/FBXgP4ivZWQ
youtu.be/MLmydWtOVrY
youtu.be/cC65lCZ_Qyk
youtu.be/2EdF0eJdYvw
youtu.be/eojxhB0NQwY
youtu.be/YOnDOuY1mSc
youtu.be/iLAYmGRmwSw
youtu.be/ijwUeUP6w_0
youtu.be/CT1AsteldDA
youtu.be/SEzOwz4f598
youtu.be/ZIlm4kV-dfQ
youtu.be/KXpc_lw9SIo
youtu.be/dzZ5twYiu3s
youtu.be/Aqzzbkmf3Kc
youtu.be/uYauzSHBjAI
youtu.be/3Ti0hUQPy5U
youtu.be/4IDf9pnks4w
youtu.be/YiPS8rgYDu4
youtu.be/_JDzWc7Tf5M
youtu.be/4R7F86fUHMo
youtu.be/wDjiI-z74kQ
youtu.be/QLXvpBcIEqc
youtu.be/cRGVvb0VHtc
youtu.be/Rnz_3fgkfIg
youtu.be/t0KQ5qXgMvE
youtu.be/c-dotbMpndQ
youtu.be/UsxvW2kDdF4
youtu.be/VULyr2BGRUU
youtu.be/Nz2Gmkczxu8
youtu.be/6RLaHPt4bcY
youtu.be/FQc3_u7V_JY
youtu.be/x1vnHPUz6WA
youtu.be/r7Gd0mric4A
youtu.be/BpRqtM2IM8w
youtu.be/-nIL_6bir7A
youtu.be/Ll9ZLBZLbhY
youtu.be/T4UlVdsUUAo
youtu.be/W3Z_fNBLU94
youtu.be/UZYDaF0suHE
youtu.be/rWVt-UBBWoA
youtu.be/cmiMKg4vlmE
youtu.be/xovCsye3VJs
youtu.be/4O1WeYiqVPI
youtu.be/TMgcME8enEU
youtu.be/i-VPViUF7v4
youtu.be/Tm321OxYJiY
youtu.be/KwC1sRp7omI
youtu.be/RL3Td7pbMzs
youtu.be/3KORnYkN34o
youtu.be/PgfrRCujskc
youtu.be/2Fs4HO8DIrU
youtu.be/xDDUdgoHnT4
youtu.be/8bnIfmid4tk
youtu.be/s19QzCF8Evw
youtu.be/qk13LEdu53c
youtu.be/5iN2A-RfFyc
youtu.be/x8demWTyDVI
youtu.be/1KpT8dSyHg4
youtu.be/O08PciPcpQg
youtu.be/fdOeYHlbFDo
youtu.be/NxwF4YrgHCU
youtu.be/S7Ar7ML9jeY
youtu.be/sbqzxZjDPAo
youtu.be/Cx3WZMb2v9I
youtu.be/eAbB62BTjj0
youtu.be/x189bOFlMQM
youtu.be/x7b7V0KeBcc
youtu.be/Ew_U0Xs3YgU
youtu.be/UEu3gSY1L7s
youtu.be/YV48rmYyFlk
youtu.be/FQ8lYHD8bIg
youtu.be/mCtDoJWaGdc
youtu.be/y6RaiLp_aXs
youtu.be/2a5tPf8gEkc
youtu.be/s2hHyOxcbGU
youtu.be/loPTJxKN8fo
youtu.be/CaESCQfKN7w
youtu.be/3xouidfZzGY

In [11]:
len(df_crime2)

896

In [12]:
df_crime2 = df_crime[df_crime["text"].str.contains("policy")]
len(df_crime2)

305

In [13]:
df_crime2 = df_crime[df_crime["text"].str.contains("trump")]
len(df_crime2)

121

In [18]:
df_crime2 = df_crime[df_crime["text"].str.contains("epstein")]
len(df_crime2)

25

In [21]:
df_crime2 = df_crime[df_crime["text"].str.contains("biden")]
len(df_crime2)

66

In [22]:
df_crime2 = df_crime[df_crime["text"].str.contains("biden")]
len(df_crime2)

66

In [20]:
from collections import Counter
import re

# juntar todo o texto do df_crime2
all_text = " ".join(df_crime2["text"].astype(str))

# tokenizar (somente letras, tudo minúsculo)
tokens = re.findall(r"\b[a-zA-Z]+\b", all_text.lower())

# remover stopwords básicas
stopwords = {"the","and","to","of","in","a","is","that","for","it","on","with","as","at","this","was","be","by","are","an","from"}

tokens_clean = [t for t in tokens if t not in stopwords]

# contar
freq = Counter(tokens_clean)

# ver as 30 mais comuns
freq.most_common(30)

[('biden', 132),
 ('child', 48),
 ('news', 39),
 ('trump', 30),
 ('business', 22),
 ('hunter', 18),
 ('trafficking', 18),
 ('administration', 17),
 ('case', 17),
 ('diddy', 17),
 ('hitler', 17),
 ('president', 16),
 ('migrant', 16),
 ('family', 15),
 ('harris', 15),
 ('policy', 14),
 ('guatemala', 14),
 ('crime', 13),
 ('parody', 13),
 ('immigration', 12),
 ('woman', 12),
 ('school', 12),
 ('texas', 12),
 ('american', 11),
 ('interview', 11),
 ('border', 11),
 ('support', 11),
 ('gender', 11),
 ('suspect', 11),
 ('parent', 11)]

In [23]:
from collections import Counter
import re

# juntar todo o texto do df_crime2
all_text = " ".join(df_saude["text"].astype(str))

# tokenizar (somente letras, tudo minúsculo)
tokens = re.findall(r"\b[a-zA-Z]+\b", all_text.lower())

# remover stopwords básicas
stopwords = {"the","and","to","of","in","a","is","that","for","it","on","with","as","at","this","was","be","by","are","an","from"}

tokens_clean = [t for t in tokens if t not in stopwords]

# contar
freq = Counter(tokens_clean)

# ver as 30 mais comuns
freq.most_common(30)

[('health', 18039),
 ('medical', 8568),
 ('covid', 6076),
 ('doctor', 5192),
 ('disease', 4722),
 ('food', 4639),
 ('vaccine', 4597),
 ('body', 4472),
 ('advice', 4453),
 ('news', 4442),
 ('berg', 4422),
 ('diet', 4306),
 ('healthy', 3969),
 ('treatment', 3960),
 ('cancer', 3776),
 ('benefit', 3710),
 ('vitamin', 3686),
 ('support', 3563),
 ('cause', 3349),
 ('physician', 3330),
 ('patient', 3323),
 ('natural', 3298),
 ('long', 2877),
 ('medicine', 2728),
 ('condition', 2649),
 ('blood', 2541),
 ('product', 2528),
 ('professional', 2522),
 ('diagnosis', 2473),
 ('question', 2462)]